export type Lang = "es" | "en";

export const WA_NUMBER = "50767555768";
export const WA_BASE = "Hola, quiero reservar en La Quinta Pata.";

export const copy = {
  es: {
    name: "La Quinta Pata",
    kicker: "Gastrobar · San Francisco, Panamá",
    heroLine: "El quinto elemento de la mesa.",
    heroSub: "Parrilla, picadas y barra. La noche manda.",
    reserve: "Reservar",
    menu: "Ver carta",
    nav: [
      { id: "carta", label: "Carta" },
      { id: "barra", label: "Barra" },
      { id: "noches", label: "Noches" },
      { id: "nosotros", label: "Nosotros" },
      { id: "visita", label: "Visítanos" },
    ],
    cartaEyebrow: "Carta viva",
    cartaTitle: "Primero se pica. Después, la parrilla.",
    cartaNote: "Carta viva. Precios en USD, con ITBMS. Sujetos a cambio.",
    bites: "Picadas",
    grill: "Parrilla",
    dishes: [
      {
        kind: "grill" as const,
        name: "Parrillada Argentina para 2",
        desc: "Pollo a la brasa, chorizo parrillero, N.Y. strip y 2 acompañamientos.",
        price: null,
        img: "/media/parrillada.webp",
      },
      {
        kind: "grill" as const,
        name: "Rib Eye a la brasa",
        desc: "Terminado en beef tallow aromatizado.",
        price: null,
        img: "/media/ribeye.webp",
      },
      {
        kind: "bite" as const,
        name: "Pork belly bites picantes",
        desc: "Dados de panza de cerdo confitada y ahumada, salsa BBQ-ajonjolí.",
        price: "$7",
        img: "/media/belly.webp",
      },
    ],
    barEyebrow: "Barra",
    barTitle: "Un vaso frío, sin teatro.",
    barLead:
      "La carta de barra, con ITBMS. Lo que no esté en servicio no aparece. Precios sujetos a cambio.",
    barItems: [
      { title: "Cócteles", body: "De la casa. Se piden en barra." },
      { title: "Cerveza", body: "Barril y botella." },
      { title: "Destilados", body: "Sin lista de marcas en la web." },
    ],
    nightsEyebrow: "Noches",
    nightsTitle: "Partido o tarima. A veces los dos.",
    nights: [
      { title: "Fútbol en vivo", body: "Pantallas. Llega cuando quieras ver el partido." },
      { title: "Música en vivo", body: "Tarima. Cuando hay función, se anuncia en Instagram." },
      { title: "Walk-in o reserva", body: "Se puede llegar sin reserva. Para grupo, mejor avisar." },
    ],
    reserveEyebrow: "Reservar",
    reserveTitle: "La mesa queda en espera.",
    reserveLead:
      "Fecha, hora y cuántos son. El botón abre WhatsApp con el mensaje escrito. La casa confirma por ahí.",
    date: "Fecha",
    time: "Hora",
    slotsLead: "Turnos de 30 min, 6:00 p. m.–11:00 p. m. La casa confirma. No es el horario publicado.",
    syncOk: "Turnos ocupados según Google Calendar.",
    syncWait: "Sincronizando con Google Calendar…",
    syncOff: "Calendario no disponible en esta vista. Igual puedes pedir un turno.",
    syncLogin: "Conectar Google Calendar",
    busy: "Ocupado",
    party: "Personas",
    guestName: "Nombre",
    guestPhone: "Teléfono / WhatsApp",
    phonePh: "6xxx-xxxx",
    sending: "Enviando…",
    saveError: "No pudimos guardar la solicitud. Tu mensaje de WhatsApp sigue siendo válido: envíalo para reservar.",
    saveWait: "Recibimos varias solicitudes desde aquí. Escríbenos por WhatsApp para cerrar la reserva.",
    saveBad: "Revisa nombre, teléfono y fecha.",
    notes: "Notas",
    notesPh: "Ocasión, mesa alta, partido…",
    send: "Enviar por WhatsApp",
    wa: "WhatsApp",
    holdTitle: "WhatsApp abierto.",
    holdBody: "El mensaje lleva fecha, hora, personas y la nota. La casa confirma por ahí. El nombre no se guarda en la página.",
    aboutEyebrow: "Nosotros",
    about: [
      "La quinta pata es lo que completa la mesa: el trago, el plato de más, la razón para quedarse. En San Francisco, ciudad de Panamá, La Quinta Pata es un gastrobar de parrilla, picadas y barra.",
      "La noche manda. Brasas, humo, un vaso frío. Pantallas para el partido y tarima cuando hay música en vivo.",
    ],
    visitEyebrow: "Visítanos",
    visitTitle: "Av. 5ta Sur, San Francisco.",
    address: "Av. 5ta Sur, San Francisco, Ciudad de Panamá",
    mapNote: "Zona de la avenida. Confirma el local por WhatsApp si vienes de lejos.",
    pay: "Visa · Mastercard · Efectivo · Yappy",
    amenities: "Estacionamiento · Wi-Fi",
    ig: "@laquintapata_pty",
    legal: "© 2026 La Quinta Pata. San Francisco, Ciudad de Panamá.",
    legal2: "Carta viva. Los precios pueden cambiar. Las reservas quedan sujetas a confirmación.",
  },
  en: {
    name: "La Quinta Pata",
    kicker: "Gastrobar · San Francisco, Panama",
    heroLine: "The fifth thing on the table.",
    heroSub: "Grill, small plates, and a bar. Night comes first.",
    reserve: "Reserve",
    menu: "See the menu",
    nav: [
      { id: "carta", label: "Menu" },
      { id: "barra", label: "Bar" },
      { id: "noches", label: "Nights" },
      { id: "nosotros", label: "About" },
      { id: "visita", label: "Visit" },
    ],
    cartaEyebrow: "Living menu",
    cartaTitle: "Bites first. Then the grill.",
    cartaNote: "Living menu. Prices in USD, ITBMS included. Subject to change.",
    bites: "Bites",
    grill: "Grill",
    dishes: [
      {
        kind: "grill" as const,
        name: "Argentine grill for 2",
        desc: "Charcoal chicken, parrillero chorizo, N.Y. strip, and 2 sides.",
        price: null,
        img: "/media/parrillada.webp",
      },
      {
        kind: "grill" as const,
        name: "Charcoal rib eye",
        desc: "Finished in aromatic beef tallow.",
        price: null,
        img: "/media/ribeye.webp",
      },
      {
        kind: "bite" as const,
        name: "Spicy pork belly bites",
        desc: "Cubes of confit, smoked pork belly with sesame BBQ sauce.",
        price: "$7",
        img: "/media/belly.webp",
      },
    ],
    barEyebrow: "Bar",
    barTitle: "A cold glass. No theater.",
    barLead:
      "The bar card, ITBMS included. Anything off service is hidden. Prices can change.",
    barItems: [
      { title: "Cocktails", body: "House drinks. Ordered at the bar." },
      { title: "Beer", body: "Draft and bottle." },
      { title: "Spirits", body: "No brand list on the site." },
    ],
    nightsEyebrow: "Nights",
    nightsTitle: "The match, or the stage. Sometimes both.",
    nights: [
      { title: "Live football", body: "Screens. Walk in when the match is on." },
      { title: "Live music", body: "A small stage. Shows are posted on Instagram." },
      { title: "Walk-in or reserve", body: "Walk-ins are welcome. For a group, send a note." },
    ],
    reserveEyebrow: "Reserve",
    reserveTitle: "The table stays on hold.",
    reserveLead:
      "Date, time, and how many. The button opens WhatsApp with the message written. The house confirms there.",
    date: "Date",
    time: "Time",
    slotsLead: "30-minute turns, 6:00–11:00 p.m. The house confirms. These are not published hours.",
    syncOk: "Busy turns come from Google Calendar.",
    syncWait: "Syncing with Google Calendar…",
    syncOff: "Calendar is not available in this view. You can still request a turn.",
    syncLogin: "Connect Google Calendar",
    busy: "Busy",
    party: "Party",
    guestName: "Name",
    guestPhone: "Phone / WhatsApp",
    phonePh: "+507 6xxx-xxxx",
    sending: "Sending…",
    saveError: "We could not save the request. Your WhatsApp message still works: send it to book.",
    saveWait: "We got several requests from here. Message us on WhatsApp to close the booking.",
    saveBad: "Check name, phone and date.",
    notes: "Notes",
    notesPh: "Occasion, high table, the match…",
    send: "Send on WhatsApp",
    wa: "WhatsApp",
    holdTitle: "WhatsApp is open.",
    holdBody: "The message has the date, time, party, and note. The house confirms there. A name is not stored on the page.",
    aboutEyebrow: "About",
    about: [
      "The fifth leg is what finishes the table: the drink, the extra plate, the reason you stay. In San Francisco, Panama City, La Quinta Pata is a gastrobar of grill, bites, and a bar.",
      "Night comes first. Embers, smoke, a cold glass. Screens for the match, and a stage when there is live music.",
    ],
    visitEyebrow: "Visit",
    visitTitle: "Av. 5ta Sur, San Francisco.",
    address: "Av. 5ta Sur, San Francisco, Panama City",
    mapNote: "The avenue. Confirm the door on WhatsApp if you are coming from far.",
    pay: "Visa · Mastercard · Cash · Yappy",
    amenities: "Parking · Wi-Fi",
    ig: "@laquintapata_pty",
    legal: "© 2026 La Quinta Pata. San Francisco, Panama City.",
    legal2: "Living menu. Prices may change. Reservations are subject to confirmation.",
  },
} as const;
