import type { Lang } from "@/lib/copy";

export const reviewsCopy = {
  es: {
    eyebrow: "Reseñas",
    title: "Lo que dice la mesa.",
    lead: "Reseñas de la casa, de Google y de otras plataformas. Las de Google y TripAdvisor se actualizan solas.",
    all: "Todas",
    empty: "Todavía no hay reseñas publicadas. Sé el primero.",
    more: "Ver más",
    less: "Ver menos",
    readMore: "Leer en",
    reply: "Respuesta de la casa",
    verified: "Visita verificada",
    reviewsWord: "reseñas",
    onPlatform: "en",
    onSite: "en este sitio",
    writeTitle: "Deja tu reseña",
    writeLead: "Se publica después de una revisión rápida. No pedimos correo ni teléfono.",
    stars: "Tu calificación",
    starLabel: (n: number) => `${n} de 5 estrellas`,
    name: "Nombre",
    namePh: "Como quieres que aparezca",
    body: "Tu experiencia",
    bodyPh: "Qué pediste, cómo te atendieron, si volverías…",
    send: "Enviar reseña",
    sending: "Enviando…",
    thanks: "Gracias. Tu reseña llegó a la casa.",
    thanksPending: "Se publica cuando la revisemos.",
    thanksLive: "Ya está publicada.",
    errWait: "Recibimos varias reseñas desde aquí. Intenta más tarde.",
    errBad: "Elige estrellas, escribe tu nombre y al menos una frase.",
    errFail: "No pudimos enviar la reseña. Intenta de nuevo.",
    google: "También puedes dejarla en Google",
    googleCta: "Reseñar en Google",
    // post-visit feedback page
    fbTitle: "¿Cómo te fue?",
    fbHello: (name: string) => (name ? `Hola ${name}.` : "Hola."),
    fbLead: (date: string) => `Gracias por venir el ${date}. Cuéntanos con sinceridad: lo bueno y lo que no.`,
    fbBody: "Comentario (opcional)",
    fbBodyPh: "Lo que más te gustó, lo que mejorarías…",
    fbPublish: "Pueden publicar mi comentario en la web (solo con mi primer nombre)",
    fbSend: "Enviar",
    fbThanks: "Gracias. Lo lee la casa directamente.",
    fbGoogle: "Si quieres, también nos ayuda mucho una reseña en Google:",
    fbDone: "Ya recibimos tu opinión sobre esta visita. ¡Gracias!",
    fbBad: "Este enlace no es válido o ya venció.",
    fbHome: "Ir al sitio",
  },
  en: {
    eyebrow: "Reviews",
    title: "What the table says.",
    lead: "Reviews from the house, Google and other platforms. Google and TripAdvisor reviews update on their own.",
    all: "All",
    empty: "No published reviews yet. Be the first.",
    more: "Show more",
    less: "Show less",
    readMore: "Read on",
    reply: "Reply from the house",
    verified: "Verified visit",
    reviewsWord: "reviews",
    onPlatform: "on",
    onSite: "on this site",
    writeTitle: "Leave a review",
    writeLead: "Published after a quick check. No email or phone needed.",
    stars: "Your rating",
    starLabel: (n: number) => `${n} out of 5 stars`,
    name: "Name",
    namePh: "How it should appear",
    body: "Your experience",
    bodyPh: "What you ordered, how the service was, would you come back…",
    send: "Send review",
    sending: "Sending…",
    thanks: "Thank you. Your review reached the house.",
    thanksPending: "It goes live once we check it.",
    thanksLive: "It's live now.",
    errWait: "We got several reviews from here. Try again later.",
    errBad: "Pick stars, add your name and at least one sentence.",
    errFail: "We couldn't send the review. Try again.",
    google: "You can also leave it on Google",
    googleCta: "Review on Google",
    fbTitle: "How was it?",
    fbHello: (name: string) => (name ? `Hi ${name}.` : "Hi."),
    fbLead: (date: string) => `Thanks for coming on ${date}. Be honest with us: the good and the not so good.`,
    fbBody: "Comment (optional)",
    fbBodyPh: "What you liked most, what you'd improve…",
    fbPublish: "You may publish my comment on the website (first name only)",
    fbSend: "Send",
    fbThanks: "Thank you. The house reads it directly.",
    fbGoogle: "If you like, a Google review helps us a lot too:",
    fbDone: "We already have your feedback for this visit. Thank you!",
    fbBad: "This link is not valid or has expired.",
    fbHome: "Go to the website",
  },
} satisfies Record<Lang, Record<string, unknown>>;
