import { emptyBook, type Venue } from "../types";

/**
 * Cervecería Tres Gatos | Taproom — pitch demo (not a client yet).
 *
 * Source: Instagram @3gatoscerveceria and public listings (Oct 2026).
 * Confirm with the house before go-live: beer list, prices, food menu, hours,
 * payment methods. WhatsApp points to Pipo's TEST number until handover.
 */
const DEMO_WA = "50764946886";

const venue: Venue = {
  slug: "tresgatos",
  name: "Tres Gatos",
  meta: {
    title: "Cervecería Tres Gatos — Taproom en Ciudad de Panamá",
    description:
      "Cervezas artesanales de la casa en barril, comida, parking y pet friendly. Taproom en Calle Augusto Samuel Boyd, Ciudad de Panamá. Reservas por WhatsApp.",
    siteUrl: "https://demo-tresgatos.pipolopez.pro",
    favicon: { href: "/favicon.png", type: "image/png" },
  },
  logo: "/logo-round.png",
  placeholder: "/logo-round.png",
  layout: { drinksFirst: true },
  theme: {
    bg: "#0d0d0e",
    surface: "#18181a",
    fg: "#f1eee6",
    muted: "#9a968c",
    accent: "#f0a630",
    ink: "#141210",
    line: "#2a2a2b",
    displayStyle: "normal",
    displayCss:
      ".font-display{letter-spacing:.015em}#nosotros p.font-display{font-family:var(--font-sans);font-weight:300;font-size:1.65rem;line-height:1.45;letter-spacing:0}",
  },
  fonts: {
    href: "https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Work+Sans:wght@300;400;500&display=swap",
    display: '"Bebas Neue", "Arial Narrow", sans-serif',
    sans: '"Work Sans", system-ui, sans-serif',
  },
  contact: {
    whatsapp: DEMO_WA,
    whatsappDisplay: "6494-6886",
    yappy: null,
    instagram: "3gatoscerveceria",
    address: "Calle Augusto Samuel Boyd, Ciudad de Panamá",
    streetAddress: "Calle Augusto Samuel Boyd",
    locality: "Ciudad de Panamá",
    footer: "Calle Augusto Samuel Boyd · 395-2998 · @3gatoscerveceria · Pet friendly",
    map: {
      embed:
        "https://www.google.com/maps?q=Cervecer%C3%ADa+3+Gatos,+Calle+Augusto+Samuel+Boyd,+Panam%C3%A1&output=embed",
      title: "Cervecería Tres Gatos, Calle Augusto Samuel Boyd, Panamá",
    },
  },
  jsonld: { type: "BarOrPub", cuisine: "Cerveza artesanal", payment: "Cash, Credit Card", telephone: "+5073952998" },
  media: {
    hero: { src: "/media/hero.svg", alt: "Torre de grifos con las cervezas de la casa" },
    bar: { src: "/media/flight.svg", alt: "Un flight de cuatro cervezas de la casa" },
    nights: { src: "/media/stage.svg", alt: "La tarima con guitarra y amplificador" },
    stage: { src: "/media/pets.svg", alt: "Un perro descansando en el taproom" },
  },
  messages: {
    reserve: "Hola, quiero reservar en Tres Gatos.",
    order: { es: "Hola, quiero pedir en Tres Gatos.", en: "Hi, I'd like to order at Tres Gatos." },
    feedback: "Hola{name}, gracias por venir a Tres Gatos. ¿Cómo te fue? Son 20 segundos: {link}",
    feedbackTitle: "¿Cómo te fue? — Tres Gatos",
  },
  copy: {
    es: {
      name: "Tres Gatos",
      kicker: "Taproom · Cervecería artesanal · Ciudad de Panamá",
      heroLine: "Todo empieza con 3 gatos.",
      heroSub: "Cervezas de la casa en barril, comida y parking del bueno. Tu perro también entra.",
      reserve: "Reservar",
      menu: "Ver las cervezas",
      nav: [
        { id: "barra", label: "Cervezas" },
        { id: "carta", label: "Comida" },
        { id: "noches", label: "Eventos" },
        { id: "nosotros", label: "Nosotros" },
        { id: "resenas", label: "Reseñas" },
        { id: "visita", label: "Visítanos" },
      ],
      cartaEyebrow: "Comida",
      cartaTitle: "Algo para acompañar la pinta.",
      cartaNote: "Demo: carta y precios por confirmar con la casa. Precios en USD, con ITBMS.",
      bites: "Para picar",
      grill: "Burgers",
      dishes: [
        { kind: "grill", name: "Smash burger", desc: "Carne aplastada a la plancha, en pan suave.", price: null, img: "" },
        { kind: "bite", name: "Papas fritas", desc: "Para la mesa.", price: null, img: "" },
      ],
      barEyebrow: "En barril",
      barTitle: "Del tanque al vaso.",
      barLead:
        "Las de la casa, servidas en barril. Lo que no está tirando hoy no aparece. Si no sabes por cuál empezar, pide un flight.",
      barItems: [
        { title: "De la casa", body: "Hechas aquí, en barril." },
        { title: "Flight", body: "Cuatro muestras para elegir tu pinta." },
        { title: "Ediciones especiales", body: "Colaboraciones por temporada." },
      ],
      nightsEyebrow: "Eventos",
      nightsTitle: "Blues en vivo, barril y perros bienvenidos.",
      nights: [
        { title: "Música en vivo", body: "Bandas en la tarima. La cartelera sale en Instagram." },
        { title: "Pet friendly", body: "Trae a tu perro. Aquí es parte de la mesa." },
        { title: "Parking del bueno", body: "Llegas, estacionas y entras. Sin vueltas." },
      ],
      reserveEyebrow: "Reservar",
      reserveTitle: "Aparta la mesa para tu manada.",
      reserveLead:
        "Fecha, hora y cuántos son. El botón abre WhatsApp con el mensaje escrito. La casa confirma por ahí.",
      date: "Fecha",
      time: "Hora",
      slotsLead: "Turnos de 30 min, 3:00–9:00 p. m., martes a sábado. La casa confirma.",
      syncOk: "Turnos ocupados según Google Calendar.",
      syncWait: "Sincronizando con Google Calendar…",
      syncOff: "Calendario no disponible en esta vista. Igual puedes pedir un turno.",
      syncLogin: "Conectar Google Calendar",
      busy: "Ocupado",
      party: "Personas",
      guestName: "Nombre",
      guestPhone: "Teléfono / WhatsApp",
      phonePh: "6xxx-xxxx",
      sending: "Enviando…",
      saveError: "No pudimos guardar la solicitud. Tu mensaje de WhatsApp sigue siendo válido: envíalo para reservar.",
      saveWait: "Recibimos varias solicitudes desde aquí. Escríbenos por WhatsApp para cerrar la reserva.",
      saveBad: "Revisa nombre, teléfono y fecha.",
      notes: "Notas",
      notesPh: "Cumpleaños, vienes con perro, mesa afuera…",
      send: "Enviar por WhatsApp",
      cart: "Pedido",
      cartTitle: "El pedido",
      cartEmpty: "Todavía no hay nada. Pide desde las cervezas o la comida.",
      cartAdd: "Pedir",
      cartMesa: "En el local",
      cartGo: "Para llevar",
      cartNote: "Nota",
      cartNotePh: "Sin cebolla, mesa afuera…",
      cartSend: "Enviar pedido por WhatsApp",
      cartTax: "ITBMS incluido",
      cartTotal: "Total",
      cartSent: "WhatsApp abierto.",
      cartSentBody:
        "El mensaje lleva el pedido y la nota. El nombre no se guarda. La casa confirma por ahí. Se paga en el local.",
      cartGone: "Ya no está.",
      cartLead: "Precios de la carta, con ITBMS. No es delivery.",
      payHow: "Cómo pagas",
      payYappy: "Yappy",
      payCard: "Tarjeta",
      payCash: "Efectivo",
      yappyLead: "Yappy a la casa. La casa confirma cuando llega.",
      yappyCopy: "Copiar número",
      yappyCopied: "Número copiado",
      yappyPhone: "Tu celular Yappy",
      yappyPhonePh: "6000-0000",
      yappyPhoneHint: "Solo para que te pidan el Yappy. No se guarda.",
      yappyPhoneBad: "El celular va con 8 dígitos, o 11 si empieza con 507.",
      cardLead: "La tarjeta se pasa en el datáfono. El número no se escribe aquí.",
      cashLead: "Efectivo en la casa.",
      payNeed: "Elige tarjeta o efectivo.",
      sentYappy: "Cuando el Yappy entre, la casa lo marca cobrado.",
      sentCard: "La casa pasa la tarjeta en el datáfono. No mandes el número por el chat.",
      sentCash: "Pagas en efectivo en la casa.",
      wa: "WhatsApp",
      holdTitle: "WhatsApp abierto.",
      holdBody: "El mensaje lleva fecha, hora, personas y la nota. La casa confirma por ahí. El nombre no se guarda en la página.",
      aboutEyebrow: "Nosotros",
      about: [
        "Todo empieza con 3 gatos. Tres Gatos es un taproom en Ciudad de Panamá: cervezas artesanales de la casa, servidas en barril.",
        "Comida para acompañar, parking de verdad y perros bienvenidos. Y si haces cerveza en casa, aquí también consigues los ingredientes.",
      ],
      visitEyebrow: "Visítanos",
      visitTitle: "Calle Augusto Samuel Boyd.",
      address: "Calle Augusto Samuel Boyd, Ciudad de Panamá",
      mapNote: "Martes 3–10 p. m. · Miércoles a sábado 3 p. m.–12 a. m. · Domingo y lunes cerrado.",
      pay: "Tarjeta · Efectivo",
      amenities: "Parking · Pet friendly",
      ig: "@3gatoscerveceria",
      legal: "© 2026 Cervecería Tres Gatos. Ciudad de Panamá.",
      legal2: "Demo preparada por pipolopez.pro. Carta, precios y horario por confirmar con la casa.",
    },
    en: {
      name: "Tres Gatos",
      kicker: "Taproom · Craft brewery · Panama City",
      heroLine: "It all starts with 3 cats.",
      heroSub: "House beers on draft, food, and real parking. Your dog comes in too.",
      reserve: "Reserve",
      menu: "See the beers",
      nav: [
        { id: "barra", label: "Beers" },
        { id: "carta", label: "Food" },
        { id: "noches", label: "Events" },
        { id: "nosotros", label: "About" },
        { id: "resenas", label: "Reviews" },
        { id: "visita", label: "Visit" },
      ],
      cartaEyebrow: "Food",
      cartaTitle: "Something to go with the pint.",
      cartaNote: "Demo: menu and prices to be confirmed with the house. Prices in USD, ITBMS included.",
      bites: "Bites",
      grill: "Burgers",
      dishes: [
        { kind: "grill", name: "Smash burger", desc: "Beef smashed on the griddle, on a soft bun.", price: null, img: "" },
        { kind: "bite", name: "Fries", desc: "For the table.", price: null, img: "" },
      ],
      barEyebrow: "On draft",
      barTitle: "From the tank to the glass.",
      barLead:
        "House beers on draft. Anything not pouring today is hidden. Not sure where to start? Order a flight.",
      barItems: [
        { title: "House beers", body: "Brewed here, on draft." },
        { title: "Flight", body: "Four tasters to pick your pint." },
        { title: "Special editions", body: "Seasonal collaborations." },
      ],
      nightsEyebrow: "Events",
      nightsTitle: "Live blues, draft beer, and dogs welcome.",
      nights: [
        { title: "Live music", body: "Bands on the stage. The lineup is posted on Instagram." },
        { title: "Pet friendly", body: "Bring your dog. Here they are part of the table." },
        { title: "Real parking", body: "Pull in, park, walk in." },
      ],
      reserveEyebrow: "Reserve",
      reserveTitle: "Hold a table for the pack.",
      reserveLead:
        "Date, time, and how many. The button opens WhatsApp with the message written. The house confirms there.",
      date: "Date",
      time: "Time",
      slotsLead: "30-minute turns, 3:00–9:00 p.m., Tuesday to Saturday. The house confirms.",
      syncOk: "Busy turns come from Google Calendar.",
      syncWait: "Syncing with Google Calendar…",
      syncOff: "Calendar is not available in this view. You can still request a turn.",
      syncLogin: "Connect Google Calendar",
      busy: "Busy",
      party: "Party",
      guestName: "Name",
      guestPhone: "Phone / WhatsApp",
      phonePh: "+507 6xxx-xxxx",
      sending: "Sending…",
      saveError: "We could not save the request. Your WhatsApp message still works: send it to book.",
      saveWait: "We got several requests from here. Message us on WhatsApp to close the booking.",
      saveBad: "Check name, phone and date.",
      notes: "Notes",
      notesPh: "Birthday, bringing a dog, outside table…",
      send: "Send on WhatsApp",
      cart: "Order",
      cartTitle: "The order",
      cartEmpty: "Nothing yet. Add from the beers or the food.",
      cartAdd: "Add",
      cartMesa: "Here",
      cartGo: "To go",
      cartNote: "Note",
      cartNotePh: "No onion, outside table…",
      cartSend: "Send order on WhatsApp",
      cartTax: "ITBMS included",
      cartTotal: "Total",
      cartSent: "WhatsApp is open.",
      cartSentBody:
        "The message has the order and the note. A name is not stored. The house confirms there. You pay at the bar.",
      cartGone: "No longer on the menu.",
      cartLead: "Menu prices, ITBMS included. This is not delivery.",
      payHow: "How you pay",
      payYappy: "Yappy",
      payCard: "Card",
      payCash: "Cash",
      yappyLead: "Yappy to the house. The house confirms when it lands.",
      yappyCopy: "Copy number",
      yappyCopied: "Number copied",
      yappyPhone: "Your Yappy phone",
      yappyPhonePh: "6000-0000",
      yappyPhoneHint: "Only so they can request the Yappy. It is not stored.",
      yappyPhoneBad: "Use 8 digits, or 11 if it starts with 507.",
      cardLead: "Cards are taken on the house terminal. The number is not typed here.",
      cashLead: "Cash at the house.",
      payNeed: "Choose card or cash.",
      sentYappy: "When the Yappy lands, the house marks it paid.",
      sentCard: "The house runs your card on the terminal. Do not send the number in the chat.",
      sentCash: "You pay cash at the house.",
      wa: "WhatsApp",
      holdTitle: "WhatsApp is open.",
      holdBody: "The message has the date, time, party, and note. The house confirms there. A name is not stored on the page.",
      aboutEyebrow: "About",
      about: [
        "It all starts with 3 cats. Tres Gatos is a taproom in Panama City: craft beer brewed in house and poured on draft.",
        "Food to go with it, real parking, and dogs welcome. If you brew at home, you can pick up ingredients here too.",
      ],
      visitEyebrow: "Visit",
      visitTitle: "Calle Augusto Samuel Boyd.",
      address: "Calle Augusto Samuel Boyd, Panama City",
      mapNote: "Tuesday 3–10 p.m. · Wednesday to Saturday 3 p.m.–12 a.m. · Closed Sunday and Monday.",
      pay: "Card · Cash",
      amenities: "Parking · Pet friendly",
      ig: "@3gatoscerveceria",
      legal: "© 2026 Cervecería Tres Gatos. Panama City.",
      legal2: "Demo by pipolopez.pro. Menu, prices, and hours to be confirmed with the house.",
    },
  },
  menu: {
    drinkSections: ["casa", "clasico", "cero"],
    drinkLabels: {
      casa: { es: "De la casa, en barril", en: "House beers, on draft" },
      clasico: { es: "Edición especial", en: "Special edition" },
      cero: { es: "Sin alcohol", en: "Zero-proof" },
    },
    // Names from the house's Instagram and guest reviews. Prices are DEMO placeholders.
    drinks: [
      { id: "oktopussy", es: "Oktopussy", en: "Oktopussy", section: "casa", price: 7, cost: 0, status: "OK", img: null },
      { id: "rocombey", es: "Rocombey", en: "Rocombey", section: "casa", price: 7, cost: 0, status: "OK", img: null },
      { id: "jungo-ipa", es: "Jungo IPA", en: "Jungo IPA", section: "casa", price: 7, cost: 0, status: "OK", img: null },
      { id: "ipa-frutas", es: "IPA de frutas", en: "Fruit IPA", section: "casa", price: 7.5, cost: 0, status: "OK", img: null },
      { id: "flight", es: "Flight · 4 muestras", en: "Flight · 4 tasters", section: "casa", price: 9, cost: 0, status: "OK", img: null },
      { id: "rocombey-jd", es: "Rocombey × Jack Daniel's", en: "Rocombey × Jack Daniel's", section: "clasico", price: 9, cost: 0, status: "OK", img: null },
      { id: "sodas", es: "Sodas", en: "Sodas", section: "cero", price: 2.5, cost: 0, status: "OK", img: null },
      { id: "agua", es: "Agua", en: "Water", section: "cero", price: 1.5, cost: 0, status: "OK", img: null },
    ],
    plateSections: ["mains", "sides"],
    plateLabels: {
      mains: { es: "Burgers", en: "Burgers" },
      sides: { es: "Para picar", en: "Bites" },
    },
    plates: [
      { id: "smash-burger", es: "Smash burger", en: "Smash burger", section: "mains", price: 11, cost: 0, portionEs: "Carne aplastada a la plancha, en pan suave.", portionEn: "Beef smashed on the griddle, on a soft bun.", img: null },
      { id: "papas", es: "Papas fritas", en: "Fries", section: "sides", price: 5, cost: 0, portionEs: "Para la mesa.", portionEn: "For the table.", img: null },
    ],
  },
  booking: {
    slots: ["15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00"],
    closedWeekdays: [0, 1],
    coversPerSlot: 20,
    autoConfirmMaxParty: 6,
    maxParty: 20,
    bookAheadDays: 60,
    minLeadMinutes: 60,
  },
  agent: {
    kind: "Taproom de cerveza artesanal (cervecería con cervezas de la casa en barril)",
    payments: "Tarjeta y efectivo (por confirmar)",
    amenities: "Parking, pet friendly",
    facts: [
      "Cervezas artesanales de la casa en barril, entre ellas Oktopussy, Rocombey y Jungo IPA.",
      "Pet friendly: se puede venir con perro.",
      "Tiene parking.",
      "Música en vivo algunas noches; se anuncia en Instagram @3gatoscerveceria.",
      "Horario: martes 3–10 p. m.; miércoles a sábado 3 p. m.–12 a. m.; domingo y lunes cerrado.",
      "Venden ingredientes para hacer cerveza en casa.",
    ],
  },
  books: { cocina: emptyBook, barra: emptyBook },
};

export default venue;
