import { emptyBook, type Venue } from "../types";

/**
 * Cervecería Tres Gatos | Taproom — pitch demo (not a client yet).
 *
 * Sources (Oct 2026): the house's own beer menu "Menu Taproom 3G marzo 2026"
 * (linked from their Taplink), their logo, Instagram @3gatoscerveceria and public
 * listings. Beer names, styles, ABV and IBU are theirs; PRICES ARE PLACEHOLDERS
 * (the menu has none). Confirm prices, food, hours and payments before go-live.
 * WhatsApp points to Pipo's TEST number until handover.
 * Not related: cervezatresgatos.com.co is a different brewery in Bogotá.
 */
const DEMO_WA = "50764946886";

const venue: Venue = {
  slug: "tresgatos",
  name: "Tres Gatos",
  meta: {
    title: "Cervecería Tres Gatos — Taproom en Ciudad de Panamá",
    description:
      "Cervezas artesanales de la casa en barril, comida, parking y pet friendly. Taproom en Calle Augusto Samuel Boyd, Ciudad de Panamá. Reservas por WhatsApp.",
    siteUrl: "https://demo-tresgatos.pipolopez.pro",
    favicon: { href: "/favicon.png", type: "image/png" },
  },
  logo: { src: "/wordmark.png", width: 412, height: 180, replacesName: true },
  placeholder: "/logo-round.png",
  layout: {
    drinksFirst: true,
    style: "label",
    highlights: [
      { icon: "pin", es: "Taproom 3G · Ciudad de Panamá", en: "Taproom 3G · Panama City" },
      { icon: "paw", es: "Pet friendly", en: "Pet friendly" },
      { icon: "parking", es: "Parking", en: "Parking" },
      { icon: "clock", es: "Mar–Sáb desde las 3 p. m.", en: "Tue–Sat from 3 p.m." },
    ],
    seal: { es: "cervezas de la casa", en: "house beers" },
    eventIcons: ["music", "paw", "parking"],
  },
  theme: {
    bg: "#101f2f",
    surface: "#15283c",
    fg: "#f2ecdc",
    muted: "#9eabbb",
    accent: "#c4b480",
    ink: "#101f2f",
    line: "#24384f",
    displayStyle: "normal",
  },
  fonts: {
    href: "https://fonts.googleapis.com/css2?family=Zilla+Slab:wght@600;700&family=Barlow+Condensed:wght@500;600&family=Work+Sans:wght@300;400;500&display=swap",
    display: '"Zilla Slab", Georgia, serif',
    sans: '"Work Sans", system-ui, sans-serif',
    label: '"Barlow Condensed", "Arial Narrow", sans-serif',
  },
  contact: {
    whatsapp: DEMO_WA,
    whatsappDisplay: "6494-6886",
    yappy: null,
    instagram: "3gatoscerveceria",
    address: "Calle Augusto Samuel Boyd, Ciudad de Panamá",
    streetAddress: "Calle Augusto Samuel Boyd",
    locality: "Ciudad de Panamá",
    footer: "Calle Augusto Samuel Boyd · 395-2998 · @3gatoscerveceria · Pet friendly",
    map: {
      embed:
        "https://www.google.com/maps?q=Cervecer%C3%ADa+3+Gatos,+Calle+Augusto+Samuel+Boyd,+Panam%C3%A1&output=embed",
      title: "Cervecería Tres Gatos, Calle Augusto Samuel Boyd, Panamá",
    },
  },
  jsonld: { type: "BarOrPub", cuisine: "Cerveza artesanal", payment: "Cash, Credit Card", telephone: "+5073952998" },
  media: {
    hero: { src: "/media/hero.svg", alt: "Torre de grifos con las cervezas de la casa" },
    bar: { src: "/media/flight.svg", alt: "Cuatro cervezas de la casa, de la rubia a la oscura" },
    nights: { src: "/media/stage.svg", alt: "La tarima con guitarra y amplificador" },
    stage: { src: "/media/pets.svg", alt: "Un perro descansando en el taproom" },
  },
  messages: {
    reserve: "Hola, quiero reservar en Tres Gatos.",
    order: { es: "Hola, quiero pedir en Tres Gatos.", en: "Hi, I'd like to order at Tres Gatos." },
    feedback: "Hola{name}, gracias por venir a Tres Gatos. ¿Cómo te fue? Son 20 segundos: {link}",
    feedbackTitle: "¿Cómo te fue? — Tres Gatos",
  },
  copy: {
    es: {
      name: "Tres Gatos",
      kicker: "Taproom 3G · Cervecería artesanal · Ciudad de Panamá",
      heroLine: "Todo empieza con 3 gatos.",
      heroSub: "Cervezas de la casa servidas en barril, de la pilsner a la imperial stout. Comida para acompañar, parking del bueno y tu perro también entra.",
      reserve: "Reservar",
      menu: "Ver las cervezas",
      nav: [
        { id: "barra", label: "Cervezas" },
        { id: "carta", label: "Comida" },
        { id: "noches", label: "Eventos" },
        { id: "nosotros", label: "Nosotros" },
        { id: "resenas", label: "Reseñas" },
        { id: "visita", label: "Visítanos" },
      ],
      cartaEyebrow: "Comida",
      cartaTitle: "Algo para acompañar la pinta.",
      cartaNote: "Demo: carta y precios por confirmar con la casa. Precios en USD, con ITBMS.",
      bites: "Para picar",
      grill: "Burgers",
      dishes: [
        { kind: "grill", name: "Smash burger", desc: "Carne aplastada a la plancha, en pan suave.", price: null, img: "" },
        { kind: "bite", name: "Papas fritas", desc: "Para la mesa.", price: null, img: "" },
      ],
      barEyebrow: "En barril",
      barTitle: "Siete familias, una barra.",
      barLead:
        "Estilo, alcohol y amargor de cada cerveza, del menú del Taproom 3G. Lo que no está tirando hoy no aparece. ¿Dudas? Pide probar antes. Demo: precios de muestra.",
      barItems: [
        { title: "De la casa", body: "Hechas aquí, en barril." },
        { title: "Siete familias", body: "De la pilsner a la imperial stout." },
        { title: "Ediciones especiales", body: "Colaboraciones por temporada." },
      ],
      nightsEyebrow: "Eventos",
      nightsTitle: "Blues en vivo, barril y perros bienvenidos.",
      nights: [
        { title: "Música en vivo", body: "Bandas en la tarima. La cartelera sale en Instagram." },
        { title: "Pet friendly", body: "Trae a tu perro. Aquí es parte de la mesa." },
        { title: "Parking del bueno", body: "Llegas, estacionas y entras. Sin vueltas." },
      ],
      reserveEyebrow: "Reservar",
      reserveTitle: "Aparta la mesa para tu manada.",
      reserveLead:
        "Fecha, hora y cuántos son. El botón abre WhatsApp con el mensaje escrito. La casa confirma por ahí.",
      date: "Fecha",
      time: "Hora",
      slotsLead: "Turnos de 30 min, 3:00–9:00 p. m., martes a sábado. La casa confirma.",
      syncOk: "Turnos ocupados según Google Calendar.",
      syncWait: "Sincronizando con Google Calendar…",
      syncOff: "Calendario no disponible en esta vista. Igual puedes pedir un turno.",
      syncLogin: "Conectar Google Calendar",
      busy: "Ocupado",
      party: "Personas",
      guestName: "Nombre",
      guestPhone: "Teléfono / WhatsApp",
      phonePh: "6xxx-xxxx",
      sending: "Enviando…",
      saveError: "No pudimos guardar la solicitud. Tu mensaje de WhatsApp sigue siendo válido: envíalo para reservar.",
      saveWait: "Recibimos varias solicitudes desde aquí. Escríbenos por WhatsApp para cerrar la reserva.",
      saveBad: "Revisa nombre, teléfono y fecha.",
      notes: "Notas",
      notesPh: "Cumpleaños, vienes con perro, mesa afuera…",
      send: "Enviar por WhatsApp",
      cart: "Pedido",
      cartTitle: "El pedido",
      cartEmpty: "Todavía no hay nada. Pide desde las cervezas o la comida.",
      cartAdd: "Pedir",
      cartMesa: "En el local",
      cartGo: "Para llevar",
      cartNote: "Nota",
      cartNotePh: "Sin cebolla, mesa afuera…",
      cartSend: "Enviar pedido por WhatsApp",
      cartTax: "ITBMS incluido",
      cartTotal: "Total",
      cartSent: "WhatsApp abierto.",
      cartSentBody:
        "El mensaje lleva el pedido y la nota. El nombre no se guarda. La casa confirma por ahí. Se paga en el local.",
      cartGone: "Ya no está.",
      cartLead: "Precios de la carta, con ITBMS. No es delivery.",
      payHow: "Cómo pagas",
      payYappy: "Yappy",
      payCard: "Tarjeta",
      payCash: "Efectivo",
      yappyLead: "Yappy a la casa. La casa confirma cuando llega.",
      yappyCopy: "Copiar número",
      yappyCopied: "Número copiado",
      yappyPhone: "Tu celular Yappy",
      yappyPhonePh: "6000-0000",
      yappyPhoneHint: "Solo para que te pidan el Yappy. No se guarda.",
      yappyPhoneBad: "El celular va con 8 dígitos, o 11 si empieza con 507.",
      cardLead: "La tarjeta se pasa en el datáfono. El número no se escribe aquí.",
      cashLead: "Efectivo en la casa.",
      payNeed: "Elige tarjeta o efectivo.",
      sentYappy: "Cuando el Yappy entre, la casa lo marca cobrado.",
      sentCard: "La casa pasa la tarjeta en el datáfono. No mandes el número por el chat.",
      sentCash: "Pagas en efectivo en la casa.",
      wa: "WhatsApp",
      holdTitle: "WhatsApp abierto.",
      holdBody: "El mensaje lleva fecha, hora, personas y la nota. La casa confirma por ahí. El nombre no se guarda en la página.",
      aboutEyebrow: "Nosotros",
      about: [
        "Todo empieza con 3 gatos. Tres Gatos es una cervecería con taproom en Ciudad de Panamá, el Taproom 3G: cervezas de la casa, de la pilsner a la imperial stout, servidas en barril.",
        "Comida para acompañar, parking de verdad y perros bienvenidos. Y si haces cerveza en casa, aquí también consigues los ingredientes.",
      ],
      visitEyebrow: "Visítanos",
      visitTitle: "Calle Augusto Samuel Boyd.",
      address: "Calle Augusto Samuel Boyd, Ciudad de Panamá",
      mapNote: "Martes 3–10 p. m. · Miércoles a sábado 3 p. m.–12 a. m. · Domingo y lunes cerrado.",
      pay: "Tarjeta · Efectivo",
      amenities: "Parking · Pet friendly",
      ig: "@3gatoscerveceria",
      legal: "© 2026 Cervecería Tres Gatos. Ciudad de Panamá.",
      legal2: "Demo preparada por pipolopez.pro. Carta, precios y horario por confirmar con la casa.",
    },
    en: {
      name: "Tres Gatos",
      kicker: "Taproom 3G · Craft brewery · Panama City",
      heroLine: "It all starts with 3 cats.",
      heroSub: "House beers poured on draft, from pilsner to imperial stout. Food to go with them, real parking, and your dog comes in too.",
      reserve: "Reserve",
      menu: "See the beers",
      nav: [
        { id: "barra", label: "Beers" },
        { id: "carta", label: "Food" },
        { id: "noches", label: "Events" },
        { id: "nosotros", label: "About" },
        { id: "resenas", label: "Reviews" },
        { id: "visita", label: "Visit" },
      ],
      cartaEyebrow: "Food",
      cartaTitle: "Something to go with the pint.",
      cartaNote: "Demo: menu and prices to be confirmed with the house. Prices in USD, ITBMS included.",
      bites: "Bites",
      grill: "Burgers",
      dishes: [
        { kind: "grill", name: "Smash burger", desc: "Beef smashed on the griddle, on a soft bun.", price: null, img: "" },
        { kind: "bite", name: "Fries", desc: "For the table.", price: null, img: "" },
      ],
      barEyebrow: "On draft",
      barTitle: "Seven families, one bar.",
      barLead:
        "Style, alcohol, and bitterness for every beer, from the Taproom 3G menu. Anything not pouring today is hidden. Not sure? Ask for a taste first. Demo: sample prices.",
      barItems: [
        { title: "House beers", body: "Brewed here, on draft." },
        { title: "Seven families", body: "From pilsner to imperial stout." },
        { title: "Special editions", body: "Seasonal collaborations." },
      ],
      nightsEyebrow: "Events",
      nightsTitle: "Live blues, draft beer, and dogs welcome.",
      nights: [
        { title: "Live music", body: "Bands on the stage. The lineup is posted on Instagram." },
        { title: "Pet friendly", body: "Bring your dog. Here they are part of the table." },
        { title: "Real parking", body: "Pull in, park, walk in." },
      ],
      reserveEyebrow: "Reserve",
      reserveTitle: "Hold a table for the pack.",
      reserveLead:
        "Date, time, and how many. The button opens WhatsApp with the message written. The house confirms there.",
      date: "Date",
      time: "Time",
      slotsLead: "30-minute turns, 3:00–9:00 p.m., Tuesday to Saturday. The house confirms.",
      syncOk: "Busy turns come from Google Calendar.",
      syncWait: "Syncing with Google Calendar…",
      syncOff: "Calendar is not available in this view. You can still request a turn.",
      syncLogin: "Connect Google Calendar",
      busy: "Busy",
      party: "Party",
      guestName: "Name",
      guestPhone: "Phone / WhatsApp",
      phonePh: "+507 6xxx-xxxx",
      sending: "Sending…",
      saveError: "We could not save the request. Your WhatsApp message still works: send it to book.",
      saveWait: "We got several requests from here. Message us on WhatsApp to close the booking.",
      saveBad: "Check name, phone and date.",
      notes: "Notes",
      notesPh: "Birthday, bringing a dog, outside table…",
      send: "Send on WhatsApp",
      cart: "Order",
      cartTitle: "The order",
      cartEmpty: "Nothing yet. Add from the beers or the food.",
      cartAdd: "Add",
      cartMesa: "Here",
      cartGo: "To go",
      cartNote: "Note",
      cartNotePh: "No onion, outside table…",
      cartSend: "Send order on WhatsApp",
      cartTax: "ITBMS included",
      cartTotal: "Total",
      cartSent: "WhatsApp is open.",
      cartSentBody:
        "The message has the order and the note. A name is not stored. The house confirms there. You pay at the bar.",
      cartGone: "No longer on the menu.",
      cartLead: "Menu prices, ITBMS included. This is not delivery.",
      payHow: "How you pay",
      payYappy: "Yappy",
      payCard: "Card",
      payCash: "Cash",
      yappyLead: "Yappy to the house. The house confirms when it lands.",
      yappyCopy: "Copy number",
      yappyCopied: "Number copied",
      yappyPhone: "Your Yappy phone",
      yappyPhonePh: "6000-0000",
      yappyPhoneHint: "Only so they can request the Yappy. It is not stored.",
      yappyPhoneBad: "Use 8 digits, or 11 if it starts with 507.",
      cardLead: "Cards are taken on the house terminal. The number is not typed here.",
      cashLead: "Cash at the house.",
      payNeed: "Choose card or cash.",
      sentYappy: "When the Yappy lands, the house marks it paid.",
      sentCard: "The house runs your card on the terminal. Do not send the number in the chat.",
      sentCash: "You pay cash at the house.",
      wa: "WhatsApp",
      holdTitle: "WhatsApp is open.",
      holdBody: "The message has the date, time, party, and note. The house confirms there. A name is not stored on the page.",
      aboutEyebrow: "About",
      about: [
        "It all starts with 3 cats. Tres Gatos is a brewery with a taproom in Panama City, Taproom 3G: house beers from pilsner to imperial stout, poured on draft.",
        "Food to go with it, real parking, and dogs welcome. If you brew at home, you can pick up ingredients here too.",
      ],
      visitEyebrow: "Visit",
      visitTitle: "Calle Augusto Samuel Boyd.",
      address: "Calle Augusto Samuel Boyd, Panama City",
      mapNote: "Tuesday 3–10 p.m. · Wednesday to Saturday 3 p.m.–12 a.m. · Closed Sunday and Monday.",
      pay: "Card · Cash",
      amenities: "Parking · Pet friendly",
      ig: "@3gatoscerveceria",
      legal: "© 2026 Cervecería Tres Gatos. Panama City.",
      legal2: "Demo by pipolopez.pro. Menu, prices, and hours to be confirmed with the house.",
    },
  },
  menu: {
    // The house menu's seven families, mapped onto the template's drink slots.
    drinkSections: ["casa", "clasico", "cerveza", "vino", "destilados", "cero", "cafe"],
    drinkLabels: {
      casa: { es: "Blondies · rubias y refrescantes", en: "Blondies · light and crisp" },
      clasico: { es: "Malt Lover · para los amantes de la malta", en: "Malt Lover · for malt fans" },
      cerveza: { es: "Hop Heads · lupulosas e intensas", en: "Hop Heads · hoppy and bold" },
      vino: { es: "Hello Darkness · oscuras y tostadas", en: "Hello Darkness · dark and roasty" },
      destilados: { es: "The Sour Batch · ácidas y fermentaciones mixtas", en: "The Sour Batch · sours and mixed ferments" },
      cero: { es: "Specials · fermentaciones especiales", en: "Specials · special ferments" },
      cafe: { es: "Mad Season · de temporada y exóticas", en: "Mad Season · seasonal and exotic" },
    },
    // Names, styles, ABV and IBU from the house menu (marzo 2026). Prices are DEMO placeholders.
    drinks: [
      { id: "der-stubentiger", es: "Der Stubentiger", en: "Der Stubentiger", section: "casa", price: 6, cost: 0, status: "OK", img: null, style: { es: "Bohemian Pilsner", en: "Bohemian Pilsner" }, abv: 4.8, ibu: 36, note: { es: "Bohemian Pilsner. Refrescante y fácil de beber, con notas de pan y un toque amargo · 4.8% · 36 IBU", en: "Bohemian Pilsner. Crisp and easy, bready with a light bitter finish · 4.8% ABV · 36 IBU" } },
      { id: "tio-caiman", es: "Tío Caimán", en: "Tío Caimán", section: "casa", price: 6, cost: 0, status: "OK", img: null, style: { es: "Lager de malta pilsner", en: "Pilsner-malt lager" }, abv: 4.3, ibu: 11, note: { es: "Lager de malta pilsner, limpia, con notas acarameladas y un final floral especiado · 4.3% · 11 IBU", en: "Pilsner-malt lager. Clean, lightly caramel, floral-spicy finish · 4.3% ABV · 11 IBU" } },
      { id: "lady-buzz", es: "Lady Buzz", en: "Lady Buzz", section: "casa", price: 6.5, cost: 0, status: "OK", img: null, style: { es: "Pale Ale · naranja sanguina y miel", en: "Pale Ale · blood orange and honey" }, abv: 6.0, ibu: 40, note: { es: "Pale Ale con naranja sanguina y miel de abeja, lúpulos nobles alemanes · 6.0% · 40 IBU", en: "Pale ale with blood orange and honey, German noble hops · 6.0% ABV · 40 IBU" } },
      { id: "al-brown", es: "Al Brown", en: "Al Brown", section: "clasico", price: 6.5, cost: 0, status: "OK", img: null, style: { es: "American Brown Ale", en: "American Brown Ale" }, abv: 3.8, ibu: 18, note: { es: "American Brown Ale. Toffee, nuez y tostado suave, final limpio y seco · 3.8% · 18 IBU", en: "American Brown Ale. Toffee, nut, soft roast, clean dry finish · 3.8% ABV · 18 IBU" } },
      { id: "hells-cat", es: "Hell's Cat", en: "Hell's Cat", section: "clasico", price: 7, cost: 0, status: "OK", img: null, style: { es: "Helles Bock", en: "Helles Bock" }, abv: 6.5, ibu: 27, note: { es: "Helles Bock. Maltosa, acaramelada y sedosa, con calidez alcohólica · 6.5% · 27 IBU", en: "Helles Bock. Malty, caramel, silky and warming · 6.5% ABV · 27 IBU" } },
      { id: "oktopussy", es: "Oktopussy", en: "Oktopussy", section: "clasico", price: 6.5, cost: 0, status: "OK", img: null, style: { es: "Lager de festival alemana", en: "German festival lager" }, abv: 5.0, ibu: 24, note: { es: "Lager de festival alemana, acaramelada y tostada, con lúpulos nobles florales · 5.0% · 24 IBU", en: "German festival lager. Caramel and toast with floral noble hops · 5.0% ABV · 24 IBU" } },
      { id: "ipl", es: "IPL", en: "IPL", section: "cerveza", price: 7, cost: 0, status: "OK", img: null, style: { es: "India Pale Lager", en: "India Pale Lager" }, abv: 5.0, ibu: 64, note: { es: "India Pale Lager. Ligera y refrescante, con lúpulo cítrico y frutal · 5.0% · 64 IBU", en: "India Pale Lager. Light and crisp with citrus, fruity hops · 5.0% ABV · 64 IBU" } },
      { id: "nekomata", es: "Nekomata", en: "Nekomata", section: "cerveza", price: 7, cost: 0, status: "OK", img: null, style: { es: "Red IPA", en: "Red IPA" }, abv: 6.0, ibu: 76, note: { es: "Red IPA cobriza, base de malta acaramelada y amargor cítrico tropical · 6.0% · 76 IBU", en: "Copper Red IPA. Caramel malt and tropical citrus bitterness · 6.0% ABV · 76 IBU" } },
      { id: "ayala-yakima", es: "Ayala Yakima", en: "Ayala Yakima", section: "cerveza", price: 7, cost: 0, status: "OK", img: null, style: { es: "Hazy IPA", en: "Hazy IPA" }, abv: 5.0, ibu: 43, note: { es: "Hazy IPA de cuerpo completo, jugosa, con lúpulos tropicales · 5.0% · 43 IBU", en: "Full-bodied, juicy Hazy IPA with tropical hops · 5.0% ABV · 43 IBU" } },
      { id: "anonima", es: "Anónima", en: "Anónima", section: "cerveza", price: 5, cost: 0, status: "OK", img: null, style: { es: "IPA sin alcohol", en: "Non-alcoholic IPA" }, abv: 0.3, ibu: 20, note: { es: "IPA sin alcohol, con aroma, amargor y frescura de lúpulo · 0.3% · 20 IBU", en: "Non-alcoholic IPA with real hop aroma and bite · 0.3% ABV · 20 IBU" } },
      { id: "hairy-porter", es: "Hairy Porter", en: "Hairy Porter", section: "vino", price: 7, cost: 0, status: "OK", img: null, style: { es: "Porter con cold brew", en: "Porter with cold brew" }, abv: 5.5, ibu: 43, note: { es: "Porter ligera con café, maltas tostadas y chocolate negro, con cold brew · 5.5% · 43 IBU", en: "Light porter with coffee, roasted malt, dark chocolate and cold brew · 5.5% ABV · 43 IBU" } },
      { id: "rocombey", es: "Rocombey", en: "Rocombey", section: "vino", price: 8, cost: 0, status: "OK", img: null, style: { es: "Imperial Stout", en: "Imperial Stout" }, abv: 8.0, ibu: 48, note: { es: "Imperial Stout. Chocolate negro, tostado y cremosa, sorprendentemente suave · 8.0% · 48 IBU", en: "Imperial Stout. Dark chocolate, roast, creamy and surprisingly smooth · 8.0% ABV · 48 IBU" } },
      { id: "lord-berginton", es: "Lord Berginton", en: "Lord Berginton", section: "destilados", price: 7, cost: 0, status: "OK", img: null, style: { es: "Berliner Weisse · mandarina", en: "Berliner Weisse · mandarin" }, abv: 3.5, ibu: 5, note: { es: "Berliner Weisse con mandarina fresca, ácida y refrescante · 3.5% · 5 IBU", en: "Berliner Weisse with fresh mandarin, tart and refreshing · 3.5% ABV · 5 IBU" } },
      { id: "madame-berri", es: "Madame Berri", en: "Madame Berri", section: "destilados", price: 7, cost: 0, status: "OK", img: null, style: { es: "Berliner Weisse · fresa", en: "Berliner Weisse · strawberry" }, abv: 3.5, ibu: 5, note: { es: "Berliner Weisse con fresas frescas, acidez suave · 3.5% · 5 IBU", en: "Berliner Weisse with fresh strawberries, gently tart · 3.5% ABV · 5 IBU" } },
      { id: "katzpie", es: "Katzpie", en: "Katzpie", section: "destilados", price: 7, cost: 0, status: "OK", img: null, style: { es: "Sour IPA", en: "Sour IPA" }, abv: 5.0, ibu: 51, note: { es: "Sour IPA, tropical, entre acidez y amargor con lúpulos frutales · 5.0% · 51 IBU", en: "Sour IPA. Tropical, tart and bitter with fruity hops · 5.0% ABV · 51 IBU" } },
      { id: "pink-gun", es: "Pink Gun", en: "Pink Gun", section: "cero", price: 6.5, cost: 0, status: "OK", img: null, style: { es: "Ginger beer con saril", en: "Ginger beer with sorrel" }, abv: 5.0, ibu: null, note: { es: "Ginger beer rosada por el saril, ligeramente picante y muy burbujeante · 5.0%", en: "Ginger beer, pink from sorrel, lightly spicy and very fizzy · 5.0% ABV" } },
      { id: "wild-cider", es: "Wild Cider", en: "Wild Cider", section: "cero", price: 6.5, cost: 0, status: "OK", img: null, style: { es: "Sidra de frutos rojos", en: "Red berry cider" }, abv: 5.0, ibu: 5, note: { es: "Sidra de manzana con frutos rojos, semi dulce y ligera · 5.0% · 5 IBU", en: "Apple cider with red berries, semi-sweet and light · 5.0% ABV · 5 IBU" } },
      { id: "jefe-schoffer", es: "Jefe Schoffer", en: "Jefe Schoffer", section: "cafe", price: 7, cost: 0, status: "OK", img: null, style: { es: "Hefeweizen con toronja", en: "Hefeweizen with grapefruit" }, abv: 3.5, ibu: 20, note: { es: "Hefeweizen con soda de toronja natural, para días calurosos · 3.5% · 20 IBU", en: "Hefeweizen with natural grapefruit soda, for hot days · 3.5% ABV · 20 IBU" } },
      { id: "lagrimas-de-diablo", es: "Lágrimas de Diablo", en: "Lágrimas de Diablo", section: "cafe", price: 7, cost: 0, status: "OK", img: null, style: { es: "Smoked Gose · ají chombo", en: "Smoked Gose · ají chombo" }, abv: 4.0, ibu: 8, note: { es: "Smoked Gose ahumada en leña local, con sal y ají chombo · 4.0% · 8 IBU", en: "Smoked Gose over local wood, with salt and ají chombo · 4.0% ABV · 8 IBU" } },
      { id: "mangoliciuos", es: "Mangoliciuos", en: "Mangoliciuos", section: "cafe", price: 7, cost: 0, status: "OK", img: null, style: { es: "Tropical IPA · mango", en: "Tropical IPA · mango" }, abv: 5.5, ibu: 55, note: { es: "Tropical IPA con mango, amargor con dulzor y frescura · 5.5% · 55 IBU", en: "Tropical IPA with mango, bitter, sweet and fresh · 5.5% ABV · 55 IBU" } },
      { id: "panita", es: "Panita", en: "Panita", section: "cafe", price: 7, cost: 0, status: "OK", img: null, style: { es: "Pale Ale · pitaya", en: "Pale Ale · pitaya" }, abv: 5.0, ibu: 35, note: { es: "Pale Ale con pitaya, rosada, fresca y semi dulce · 5.0% · 35 IBU", en: "Pale ale with pitaya, pink, fresh and semi-sweet · 5.0% ABV · 35 IBU" } },
      { id: "rocombey-jd", es: "Rocombey × Jack Daniel's", en: "Rocombey × Jack Daniel's", section: "cafe", price: 9, cost: 0, status: "OK", img: null, style: { es: "Edición especial en barril", en: "Special edition on draft" }, note: { es: "Edición especial en barril: la imperial stout de la casa con Jack Daniel's", en: "Special edition on draft: the house imperial stout with Jack Daniel's" } },
    ],
    plateSections: ["mains", "sides"],
    plateLabels: {
      mains: { es: "Burgers", en: "Burgers" },
      sides: { es: "Para picar", en: "Bites" },
    },
    plates: [
      { id: "smash-burger", es: "Smash burger", en: "Smash burger", section: "mains", price: 11, cost: 0, portionEs: "Carne aplastada a la plancha, en pan suave.", portionEn: "Beef smashed on the griddle, on a soft bun.", img: null },
      { id: "papas", es: "Papas fritas", en: "Fries", section: "sides", price: 5, cost: 0, portionEs: "Para la mesa.", portionEn: "For the table.", img: null },
    ],
  },
  booking: {
    slots: ["15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00"],
    closedWeekdays: [0, 1],
    coversPerSlot: 20,
    autoConfirmMaxParty: 6,
    maxParty: 20,
    bookAheadDays: 60,
    minLeadMinutes: 60,
  },
  agent: {
    kind: "Taproom de cerveza artesanal (cervecería con cervezas de la casa en barril)",
    payments: "Tarjeta y efectivo (por confirmar)",
    amenities: "Parking, pet friendly",
    facts: [
      "Cervezas de la casa en barril en siete familias: Blondies, Malt Lover, Hop Heads, Hello Darkness, The Sour Batch, Specials y Mad Season.",
      "Algunas: Der Stubentiger (pilsner), Oktopussy (lager de festival), Nekomata (Red IPA), Rocombey (imperial stout), Katzpie (sour IPA) y Anónima (IPA sin alcohol).",
      "El taproom se llama Taproom 3G.",
      "Pet friendly: se puede venir con perro.",
      "Tiene parking.",
      "Música en vivo algunas noches; se anuncia en Instagram @3gatoscerveceria.",
      "Horario: martes 3–10 p. m.; miércoles a sábado 3 p. m.–12 a. m.; domingo y lunes cerrado.",
      "Venden ingredientes para hacer cerveza en casa.",
    ],
  },
  books: { cocina: emptyBook, barra: emptyBook },
};

export default venue;
