import type { Venue } from "../types";
import { book as barra } from "./barra";
import { book as cocina } from "./cocina";

/** La Quinta Pata Gastro Bar — the reference venue. Production: laquintapata.pipolopez.pro */
const venue: Venue = {
  slug: "laquintapata",
  name: "La Quinta Pata",
  meta: {
    title: "La Quinta Pata — Gastrobar en San Francisco, Panamá",
    description:
      "Gastrobar de parrilla, picadas y barra en Av. 5ta Sur, San Francisco, Ciudad de Panamá. Reservas por WhatsApp.",
    siteUrl: "https://laquintapata.pipolopez.pro",
  },
  theme: {
    bg: "#110f0d",
    surface: "#1a1714",
    fg: "#f3eadc",
    muted: "#a39688",
    accent: "#c4a574",
    ink: "#1a120c",
    line: "#2c2621",
    displayStyle: "italic",
  },
  fonts: {
    href: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,500;0,600;1,500&family=Outfit:wght@300;400;500&display=swap",
    display: "\"Cormorant Garamond\", \"Times New Roman\", serif",
    sans: "\"Outfit\", system-ui, sans-serif",
  },
  contact: {
    whatsapp: "50764946886",
    whatsappDisplay: "6494-6886",
    yappy: "64946886",
    instagram: "laquintapata_pty",
    address: "Av. 5ta Sur, San Francisco, Ciudad de Panamá",
    streetAddress: "Av. 5ta Sur",
    locality: "San Francisco",
    footer: "Av. 5ta Sur, San Francisco · 6494-6886 · @laquintapata_pty · Yappy",
    map: {
      embed:
        "https://www.openstreetmap.org/export/embed.html?bbox=-79.508%2C8.987%2C-79.496%2C8.995&layer=mapnik&marker=8.9912661%2C-79.5020383",
      title: "Av. 5ta Sur, San Francisco, Panamá",
    },
  },
  jsonld: { type: "Restaurant", cuisine: "Gastrobar", payment: "Cash, Visa, Mastercard, Yappy", telephone: "+507****6886" },
  media: {
    hero: { src: "/media/hero.webp", alt: "Brasa en la parrilla de La Quinta Pata" },
    bar: { src: "/media/bar.webp", alt: "La barra, de noche" },
    nights: { src: "/media/match.webp", alt: "El salón con el partido en las pantallas" },
    stage: { src: "/media/stage.webp", alt: "Tarima para música en vivo" },
  },
  messages: {
    reserve: "Hola, quiero reservar en La Quinta Pata.",
    order: { es: "Hola, quiero pedir en La Quinta Pata.", en: "Hi, I'd like to order at La Quinta Pata." },
    feedback: "Hola{name}, gracias por venir a La Quinta Pata. ¿Cómo te fue? Son 20 segundos: {link}",
    feedbackTitle: "¿Cómo te fue? — La Quinta Pata",
  },
  copy: {
  es: {
    name: "La Quinta Pata",
    kicker: "Gastrobar · San Francisco, Panamá",
    heroLine: "El quinto elemento de la mesa.",
    heroSub: "Parrilla, picadas y barra. La noche manda.",
    reserve: "Reservar",
    menu: "Ver carta",
    nav: [
      { id: "carta", label: "Carta" },
      { id: "barra", label: "Barra" },
      { id: "noches", label: "Noches" },
      { id: "nosotros", label: "Nosotros" },
      { id: "resenas", label: "Reseñas" },
      { id: "visita", label: "Visítanos" },
    ],
    cartaEyebrow: "Carta viva",
    cartaTitle: "Primero se pica. Después, la parrilla.",
    cartaNote: "Carta viva. Precios en USD, con ITBMS. Sujetos a cambio.",
    bites: "Picadas",
    grill: "Parrilla",
    dishes: [
      {
        kind: "grill",
        name: "Parrillada Argentina para 2",
        desc: "Pollo a la brasa, chorizo parrillero, N.Y. strip y 2 acompañamientos.",
        price: null,
        img: "/media/parrillada.webp",
      },
      {
        kind: "grill",
        name: "Rib Eye a la brasa",
        desc: "Terminado en beef tallow aromatizado.",
        price: null,
        img: "/media/ribeye.webp",
      },
      {
        kind: "bite",
        name: "Pork belly bites picantes",
        desc: "Dados de panza de cerdo confitada y ahumada, salsa BBQ-ajonjolí.",
        price: "$7",
        img: "/media/belly.webp",
      },
    ],
    barEyebrow: "Barra",
    barTitle: "Un vaso frío, sin teatro.",
    barLead:
      "La carta de barra, con ITBMS. Lo que no esté en servicio no aparece. Precios sujetos a cambio.",
    barItems: [
      { title: "Cócteles", body: "De la casa. Se piden en barra." },
      { title: "Cerveza", body: "Barril y botella." },
      { title: "Destilados", body: "Sin lista de marcas en la web." },
    ],
    nightsEyebrow: "Noches",
    nightsTitle: "Partido o tarima. A veces los dos.",
    nights: [
      { title: "Fútbol en vivo", body: "Pantallas. Llega cuando quieras ver el partido." },
      { title: "Música en vivo", body: "Tarima. Cuando hay función, se anuncia en Instagram." },
      { title: "Walk-in o reserva", body: "Se puede llegar sin reserva. Para grupo, mejor avisar." },
    ],
    reserveEyebrow: "Reservar",
    reserveTitle: "La mesa queda en espera.",
    reserveLead:
      "Fecha, hora y cuántos son. El botón abre WhatsApp con el mensaje escrito. La casa confirma por ahí.",
    date: "Fecha",
    time: "Hora",
    slotsLead: "Turnos de 30 min, 6:00 p. m.–11:00 p. m. La casa confirma. No es el horario publicado.",
    syncOk: "Turnos ocupados según Google Calendar.",
    syncWait: "Sincronizando con Google Calendar…",
    syncOff: "Calendario no disponible en esta vista. Igual puedes pedir un turno.",
    syncLogin: "Conectar Google Calendar",
    busy: "Ocupado",
    party: "Personas",
    guestName: "Nombre",
    guestPhone: "Teléfono / WhatsApp",
    phonePh: "6xxx-xxxx",
    sending: "Enviando…",
    saveError: "No pudimos guardar la solicitud. Tu mensaje de WhatsApp sigue siendo válido: envíalo para reservar.",
    saveWait: "Recibimos varias solicitudes desde aquí. Escríbenos por WhatsApp para cerrar la reserva.",
    saveBad: "Revisa nombre, teléfono y fecha.",
    notes: "Notas",
    notesPh: "Ocasión, mesa alta, partido…",
    send: "Enviar por WhatsApp",
    cart: "Pedido",
    cartTitle: "El pedido",
    cartEmpty: "Todavía no hay nada. Pide desde la carta o la barra.",
    cartAdd: "Pedir",
    cartMesa: "En el local",
    cartGo: "Para llevar",
    cartNote: "Nota",
    cartNotePh: "Sin cebolla, mesa alta…",
    cartSend: "Enviar pedido por WhatsApp",
    cartTax: "ITBMS incluido",
    cartTotal: "Total",
    cartSent: "WhatsApp abierto.",
    cartSentBody:
      "El mensaje lleva el pedido y la nota. El nombre no se guarda. La casa confirma por ahí. Se paga en el local: Visa, Mastercard, efectivo o Yappy.",
    cartGone: "Ya no está.",
    cartLead: "Precios de la carta, con ITBMS. No es delivery.",
    payHow: "Cómo pagas",
    payYappy: "Yappy",
    payCard: "Tarjeta",
    payCash: "Efectivo",
    yappyLead: "Manda el monto al 6494-6886. La casa confirma cuando el Yappy llega. Esta página no cobra sola.",
    yappyCopy: "Copiar 6494-6886",
    yappyCopied: "Número copiado",
    yappyPhone: "Tu celular Yappy",
    yappyPhonePh: "6000-0000",
    yappyPhoneHint: "Solo para que te pidan el Yappy. No se guarda.",
    yappyPhoneBad: "El celular va con 8 dígitos, o 11 si empieza con 507.",
    cardLead: "Visa o Mastercard se pasa en el datáfono. El número de la tarjeta no se escribe aquí.",
    cashLead: "Efectivo en la casa.",
    payNeed: "Elige Yappy, tarjeta o efectivo.",
    sentYappy: "Cuando el Yappy entre al 6494-6886, la casa lo marca cobrado.",
    sentCard: "La casa pasa Visa o Mastercard en el datáfono. No mandes el número de la tarjeta por el chat.",
    sentCash: "Pagas en efectivo en la casa.",
    wa: "WhatsApp",
    holdTitle: "WhatsApp abierto.",
    holdBody: "El mensaje lleva fecha, hora, personas y la nota. La casa confirma por ahí. El nombre no se guarda en la página.",
    aboutEyebrow: "Nosotros",
    about: [
      "La quinta pata es lo que completa la mesa: el trago, el plato de más, la razón para quedarse. En San Francisco, ciudad de Panamá, La Quinta Pata es un gastrobar de parrilla, picadas y barra.",
      "La noche manda. Brasas, humo, un vaso frío. Pantallas para el partido y tarima cuando hay música en vivo.",
    ],
    visitEyebrow: "Visítanos",
    visitTitle: "Av. 5ta Sur, San Francisco.",
    address: "Av. 5ta Sur, San Francisco, Ciudad de Panamá",
    mapNote: "Zona de la avenida. Confirma el local por WhatsApp si vienes de lejos.",
    pay: "Visa · Mastercard · Efectivo · Yappy",
    amenities: "Estacionamiento · Wi-Fi",
    ig: "@laquintapata_pty",
    legal: "© 2026 La Quinta Pata. San Francisco, Ciudad de Panamá.",
    legal2: "Carta viva. Los precios pueden cambiar. Las reservas quedan sujetas a confirmación.",
  },
  en: {
    name: "La Quinta Pata",
    kicker: "Gastrobar · San Francisco, Panama",
    heroLine: "The fifth thing on the table.",
    heroSub: "Grill, small plates, and a bar. Night comes first.",
    reserve: "Reserve",
    menu: "See the menu",
    nav: [
      { id: "carta", label: "Menu" },
      { id: "barra", label: "Bar" },
      { id: "noches", label: "Nights" },
      { id: "nosotros", label: "About" },
      { id: "resenas", label: "Reviews" },
      { id: "visita", label: "Visit" },
    ],
    cartaEyebrow: "Living menu",
    cartaTitle: "Bites first. Then the grill.",
    cartaNote: "Living menu. Prices in USD, ITBMS included. Subject to change.",
    bites: "Bites",
    grill: "Grill",
    dishes: [
      {
        kind: "grill",
        name: "Argentine grill for 2",
        desc: "Charcoal chicken, parrillero chorizo, N.Y. strip, and 2 sides.",
        price: null,
        img: "/media/parrillada.webp",
      },
      {
        kind: "grill",
        name: "Charcoal rib eye",
        desc: "Finished in aromatic beef tallow.",
        price: null,
        img: "/media/ribeye.webp",
      },
      {
        kind: "bite",
        name: "Spicy pork belly bites",
        desc: "Cubes of confit, smoked pork belly with sesame BBQ sauce.",
        price: "$7",
        img: "/media/belly.webp",
      },
    ],
    barEyebrow: "Bar",
    barTitle: "A cold glass. No theater.",
    barLead:
      "The bar card, ITBMS included. Anything off service is hidden. Prices can change.",
    barItems: [
      { title: "Cocktails", body: "House drinks. Ordered at the bar." },
      { title: "Beer", body: "Draft and bottle." },
      { title: "Spirits", body: "No brand list on the site." },
    ],
    nightsEyebrow: "Nights",
    nightsTitle: "The match, or the stage. Sometimes both.",
    nights: [
      { title: "Live football", body: "Screens. Walk in when the match is on." },
      { title: "Live music", body: "A small stage. Shows are posted on Instagram." },
      { title: "Walk-in or reserve", body: "Walk-ins are welcome. For a group, send a note." },
    ],
    reserveEyebrow: "Reserve",
    reserveTitle: "The table stays on hold.",
    reserveLead:
      "Date, time, and how many. The button opens WhatsApp with the message written. The house confirms there.",
    date: "Date",
    time: "Time",
    slotsLead: "30-minute turns, 6:00–11:00 p.m. The house confirms. These are not published hours.",
    syncOk: "Busy turns come from Google Calendar.",
    syncWait: "Syncing with Google Calendar…",
    syncOff: "Calendar is not available in this view. You can still request a turn.",
    syncLogin: "Connect Google Calendar",
    busy: "Busy",
    party: "Party",
    guestName: "Name",
    guestPhone: "Phone / WhatsApp",
    phonePh: "+507 6xxx-xxxx",
    sending: "Sending…",
    saveError: "We could not save the request. Your WhatsApp message still works: send it to book.",
    saveWait: "We got several requests from here. Message us on WhatsApp to close the booking.",
    saveBad: "Check name, phone and date.",
    notes: "Notes",
    notesPh: "Occasion, high table, the match…",
    send: "Send on WhatsApp",
    cart: "Order",
    cartTitle: "The order",
    cartEmpty: "Nothing yet. Add from the menu or the bar.",
    cartAdd: "Add",
    cartMesa: "Here",
    cartGo: "To go",
    cartNote: "Note",
    cartNotePh: "No onion, high table…",
    cartSend: "Send order on WhatsApp",
    cartTax: "ITBMS included",
    cartTotal: "Total",
    cartSent: "WhatsApp is open.",
    cartSentBody:
      "The message has the order and the note. A name is not stored. The house confirms there. You pay at the bar: Visa, Mastercard, cash, or Yappy.",
    cartGone: "No longer on the menu.",
    cartLead: "Menu prices, ITBMS included. This is not delivery.",
    payHow: "How you pay",
    payYappy: "Yappy",
    payCard: "Card",
    payCash: "Cash",
    yappyLead: "Send the amount to 6494-6886. The house confirms when Yappy lands. This page does not charge by itself.",
    yappyCopy: "Copy 6494-6886",
    yappyCopied: "Number copied",
    yappyPhone: "Your Yappy phone",
    yappyPhonePh: "6000-0000",
    yappyPhoneHint: "Only so they can request the Yappy. It is not stored.",
    yappyPhoneBad: "Use 8 digits, or 11 if it starts with 507.",
    cardLead: "Visa or Mastercard is taken on the house terminal. The card number is not typed here.",
    cashLead: "Cash at the house.",
    payNeed: "Choose Yappy, card, or cash.",
    sentYappy: "When the Yappy hits 6494-6886, the house marks it paid.",
    sentCard: "The house runs Visa or Mastercard on the terminal. Do not send the card number in the chat.",
    sentCash: "You pay cash at the house.",
    wa: "WhatsApp",
    holdTitle: "WhatsApp is open.",
    holdBody: "The message has the date, time, party, and note. The house confirms there. A name is not stored on the page.",
    aboutEyebrow: "About",
    about: [
      "The fifth leg is what finishes the table: the drink, the extra plate, the reason you stay. In San Francisco, Panama City, La Quinta Pata is a gastrobar of grill, bites, and a bar.",
      "Night comes first. Embers, smoke, a cold glass. Screens for the match, and a stage when there is live music.",
    ],
    visitEyebrow: "Visit",
    visitTitle: "Av. 5ta Sur, San Francisco.",
    address: "Av. 5ta Sur, San Francisco, Panama City",
    mapNote: "The avenue. Confirm the door on WhatsApp if you are coming from far.",
    pay: "Visa · Mastercard · Cash · Yappy",
    amenities: "Parking · Wi-Fi",
    ig: "@laquintapata_pty",
    legal: "© 2026 La Quinta Pata. San Francisco, Panama City.",
    legal2: "Living menu. Prices may change. Reservations are subject to confirmation.",
  },
  },
  menu: {
    drinkSections: ["casa", "clasico", "cerveza", "vino", "destilados", "cero", "cafe"],
    drinks: [
  { id: "canal-mule", es: "Canal Mule", en: "Canal Mule", section: "casa", price: 7, cost: 0, status: "OK", img: "/img/cocteles/canal-mule.svg" },
  { id: "oaxaca-paloma", es: "Oaxaca Paloma", en: "Oaxaca Paloma", section: "casa", price: 8, cost: 0, status: "OK", img: "/img/cocteles/oaxaca-paloma.svg" },
  { id: "havana-maracuya", es: "Havana Maracuyá", en: "Havana Maracuyá", section: "casa", price: 8, cost: 0, status: "OK", img: "/img/cocteles/havana-maracuya.svg" },
  { id: "lima-chilcano", es: "Lima Chilcano", en: "Lima Chilcano", section: "casa", price: 8, cost: 0, status: "OK", img: "/img/cocteles/lima-chilcano.svg" },
  { id: "lisboa-spritz", es: "Lisboa Spritz", en: "Lisboa Spritz", section: "casa", price: 8, cost: 0, status: "OK", img: "/img/cocteles/lisboa-spritz.svg" },
  { id: "bangkok-smash", es: "Bangkok Smash", en: "Bangkok Smash", section: "casa", price: 8, cost: 0, status: "OK", img: "/img/cocteles/bangkok-smash.svg" },
  { id: "kyoto-highball", es: "Kyoto Highball", en: "Kyoto Highball", section: "casa", price: 9, cost: 0, status: "OK", img: "/img/cocteles/kyoto-highball.svg" },
  { id: "milano-sbagliato", es: "Milano Sbagliato", en: "Milano Sbagliato", section: "casa", price: 9, cost: 0, status: "OK", img: "/img/cocteles/milano-sbagliato.svg" },
  { id: "margarita-limon", es: "Margarita de limón", en: "Lime margarita", section: "clasico", price: 7, cost: 0, status: "OK", img: "/img/cocteles/margarita-de-limon.svg" },
  { id: "margarita-maracuya", es: "Margarita de maracuyá", en: "Passion fruit margarita", section: "clasico", price: 7, cost: 0, status: "OK", img: "/img/cocteles/margarita-de-maracuya.svg" },
  { id: "margarita-jamaica", es: "Margarita de flor de Jamaica", en: "Hibiscus margarita", section: "clasico", price: 9, cost: 0, status: "OK", img: "/img/cocteles/margarita-de-flor-de-jamaica.svg" },
  { id: "mojito-limon", es: "Mojito de limón", en: "Lime mojito", section: "clasico", price: 7, cost: 0, status: "OK", img: "/img/cocteles/mojito-de-limon.svg" },
  { id: "mojito-maracuya", es: "Mojito de maracuyá", en: "Passion fruit mojito", section: "clasico", price: 7, cost: 0, status: "OK", img: "/img/cocteles/mojito-de-maracuya.svg" },
  { id: "whisky-sour", es: "Whisky Sour", en: "Whisky Sour", section: "clasico", price: 9, cost: 0, status: "OK", img: "/img/cocteles/whisky-sour.svg" },
  { id: "sour-apple", es: "Sour Apple Martini", en: "Sour Apple Martini", section: "clasico", price: 8, cost: 0, status: "OK", img: "/img/cocteles/sour-apple-martini.svg" },
  { id: "cosmopolitan", es: "Cosmopolitan", en: "Cosmopolitan", section: "clasico", price: 8, cost: 0, status: "OK", img: "/img/cocteles/cosmopolitan.svg" },
  { id: "caipirinha", es: "Caipirinha", en: "Caipirinha", section: "clasico", price: 7, cost: 0, status: "OK", img: "/img/cocteles/caipirinha.svg" },
  { id: "caipiroska", es: "Caipiroska", en: "Caipiroska", section: "clasico", price: 7, cost: 0, status: "OK", img: "/img/cocteles/caipiroska.svg" },
  { id: "daiquiri", es: "Daiquirí", en: "Daiquiri", section: "clasico", price: 7, cost: 0, status: "OK", img: "/img/cocteles/daiquiri.svg" },
  { id: "aperol", es: "Aperol Spritz", en: "Aperol Spritz", section: "clasico", price: 8, cost: 0, status: "OK", img: "/img/cocteles/aperol-spritz.svg" },
  { id: "cuba-libre", es: "Cuba Libre", en: "Cuba Libre", section: "clasico", price: 7, cost: 0, status: "OK", img: "/img/cocteles/cuba-libre.svg" },
  { id: "old-fashioned", es: "Old Fashioned", en: "Old Fashioned", section: "clasico", price: 9, cost: 0, status: "OK", img: "/img/cocteles/old-fashioned.svg" },
  { id: "gin-tonic", es: "Gin Tonic", en: "Gin & Tonic", section: "clasico", price: 7, cost: 0, status: "OK", img: "/img/cocteles/gin-tonic.svg" },
  { id: "michelada", es: "Michelada", en: "Michelada", section: "clasico", price: 6, cost: 0, status: "OK", img: "/img/cocteles/michelada.svg" },
  { id: "cerveza-nacional", es: "Cerveza nacional", en: "Local lager", section: "cerveza", price: 3, cost: 0, status: "OK", img: null },
  { id: "cerveza-importada", es: "Cerveza importada", en: "Imported lager", section: "cerveza", price: 4.5, cost: 0, status: "OK", img: null },
  { id: "artesanal", es: "Artesanal panameña, rotativa", en: "Panamanian craft, rotating", section: "cerveza", price: 6, cost: 0, status: "OK", img: null },
  { id: "cubeta", es: "Cubeta · 5 nacionales", en: "Bucket · 5 local lagers", section: "cerveza", price: 13, cost: 0, status: "OK", img: null },
  { id: "michelada-extra", es: "Michelada (extra +2)", en: "Michelada upgrade (+2)", section: "cerveza", price: 2, cost: 0, status: "OK", img: null },
  { id: "malbec-copa", es: "Malbec (copa)", en: "Malbec (glass)", section: "vino", price: 7, cost: 0, status: "OK", img: null },
  { id: "malbec-botella", es: "Malbec (botella)", en: "Malbec (bottle)", section: "vino", price: 28, cost: 0, status: "OK", img: null },
  { id: "tempranillo-copa", es: "Tempranillo (copa)", en: "Tempranillo (glass)", section: "vino", price: 7, cost: 0, status: "OK", img: null },
  { id: "tempranillo-botella", es: "Tempranillo (botella)", en: "Tempranillo (bottle)", section: "vino", price: 28, cost: 0, status: "OK", img: null },
  { id: "sauvignon-copa", es: "Sauvignon Blanc (copa)", en: "Sauvignon Blanc (glass)", section: "vino", price: 6, cost: 0, status: "OK", img: null },
  { id: "sauvignon-botella", es: "Sauvignon Blanc (botella)", en: "Sauvignon Blanc (bottle)", section: "vino", price: 26, cost: 0, status: "OK", img: null },
  { id: "rosado-copa", es: "Rosado (copa)", en: "Rosé (glass)", section: "vino", price: 7, cost: 0, status: "OK", img: null },
  { id: "rosado-botella", es: "Rosado (botella)", en: "Rosé (bottle)", section: "vino", price: 28, cost: 0, status: "OK", img: null },
  { id: "prosecco-copa", es: "Prosecco (copa)", en: "Prosecco (glass)", section: "vino", price: 7, cost: 0, status: "OK", img: null },
  { id: "prosecco-botella", es: "Prosecco (botella)", en: "Prosecco (bottle)", section: "vino", price: 30, cost: 0, status: "OK", img: null },
  { id: "sangria", es: "Sangría tinta (copa)", en: "Red sangría (glass)", section: "vino", price: 7, cost: 0, status: "OK", img: null },
  { id: "ron-anejo", es: "Ron añejo panameño", en: "Panamanian aged rum", section: "destilados", price: 6, cost: 0, status: "OK", img: null },
  { id: "seco", es: "Seco Herrerano", en: "Seco Herrerano", section: "destilados", price: 4, cost: 0, status: "OK", img: null },
  { id: "vodka", es: "Vodka", en: "Vodka", section: "destilados", price: 5, cost: 0, status: "OK", img: null },
  { id: "ginebra", es: "Ginebra", en: "Gin", section: "destilados", price: 6, cost: 0, status: "OK", img: null },
  { id: "tequila", es: "Tequila blanco", en: "Tequila blanco", section: "destilados", price: 6, cost: 0, status: "OK", img: null },
  { id: "pisco", es: "Pisco", en: "Pisco", section: "destilados", price: 6, cost: 0, status: "OK", img: null },
  { id: "whisky", es: "Whisky", en: "Whisky", section: "destilados", price: 7, cost: 0, status: "OK", img: null },
  { id: "mezcal", es: "Mezcal", en: "Mezcal", section: "destilados", price: 8, cost: 0, status: "OK", img: null },
  { id: "saril", es: "Saril Cooler", en: "Saril Cooler", section: "cero", price: 4, cost: 0, status: "OK", img: "/img/cocteles/saril-cooler.svg" },
  { id: "tonica-maracuya", es: "Tónica de Maracuyá", en: "Maracuyá Tonic", section: "cero", price: 4, cost: 0, status: "OK", img: "/img/cocteles/tonica-de-maracuya.svg" },
  { id: "limonada", es: "Limonada de Hierba de Limón", en: "Lemongrass Lemonade", section: "cero", price: 4, cost: 0, status: "OK", img: "/img/cocteles/limonada-de-hierba-de-limon.svg" },
  { id: "chicha", es: "Chicha de piña (vaso)", en: "Pineapple chicha (glass)", section: "cero", price: 3, cost: 0, status: "OK", img: null },
  { id: "sodas", es: "Sodas y agua con gas", en: "Sodas & sparkling water", section: "cero", price: 2.5, cost: 0, status: "OK", img: null },
  { id: "espresso", es: "Espresso de Boquete", en: "Boquete espresso", section: "cafe", price: 2.5, cost: 0, status: "OK", img: null },
  { id: "carajillo", es: "Carajillo", en: "Carajillo", section: "cafe", price: 7, cost: 0, status: "OK", img: null },
    ],
    plateSections: ["tapitas", "entradas", "mains", "kids", "sides", "empacados"],
    plates: [
  // ── Tapitas ─────────────────────────────────────────────────
  { id: "spicy-pork-belly-bites", es: "Spicy pork belly bites", en: "Spicy pork belly bites", section: "tapitas", price: 6, cost: 0, portionEs: "Daditos de panza de cerdo ahumados, servidos con salsa picante de BBQ y ajonjolí.", portionEn: "Smoked pork belly bites, served with spicy BBQ sauce and sesame.", img: null },

  // ── Entradas ────────────────────────────────────────────────
  { id: "chicharrones", es: "Chicharroncitos del Burro", en: "Burro pork cracklings", section: "entradas", price: 14, cost: 0, portionEs: "Panza de puerco sazonada con toque especial de la casa.", portionEn: "Pork belly seasoned with the house special touch.", img: "/media/belly.webp" },
  { id: "sliders", es: "Mini Sliders Angus Burgers", en: "Angus burger sliders", section: "entradas", price: 12, cost: 0, portionEs: "3 unid. Carne Angus, cebolla caramelizada, pepinillos y salsa de la casa en pan brioche.", portionEn: "3 pc. Angus beef, caramelized onion, pickles and house sauce on brioche.", img: "/media/sliders.webp" },
  { id: "nachos-carne", es: "Nachos de carne o pollo", en: "Beef or chicken nachos", section: "entradas", price: 15, cost: 0, portionEs: "Totopos, pico de gallo, guacamole, quesos y crema.", portionEn: "Tortilla chips, pico de gallo, guacamole, cheeses and cream.", img: "/media/nachos-carne.webp" },
  { id: "chorizo-parrillero", es: "Chorizo parrillero", en: "Grilling chorizo", section: "entradas", price: 10, cost: 0, portionEs: "Servido con cebolla caramelizada y chimichurri.", portionEn: "Served with caramelized onion and chimichurri.", img: null },
  { id: "aranitas", es: "Arañitas", en: "Plantain arañitas", section: "entradas", price: 11, cost: 0, portionEs: "Apanadas, con tártara casera.", portionEn: "Breaded, with house tartar.", img: "/media/aranitas.webp" },
  { id: "poppers", es: "Jalapeño Poppers", en: "Jalapeño poppers", section: "entradas", price: 8, cost: 0, portionEs: "Jalapeño y queso apanados.", portionEn: "Breaded jalapeño and cheese.", img: "/media/poppers.webp" },
  { id: "empanadas", es: "Empanadas de maíz", en: "Corn empanadas", section: "entradas", price: 7.5, cost: 0, portionEs: "Rellenas de carne mechada. Incluye 4 unid.", portionEn: "Stuffed with shredded beef. Includes 4 pc.", img: "/media/empanadas.webp" },
  { id: "wings", es: "Buffalo Wings", en: "Buffalo wings", section: "entradas", price: 9.5, cost: 0, portionEs: "Alitas apanadas con salsa búfalo aparte.", portionEn: "Breaded wings with buffalo sauce on the side.", img: "/media/wings.webp" },
  { id: "alitas-jerk", es: "Alitas estilo jerk jamaiquino", en: "Jamaican jerk wings", section: "entradas", price: 10.5, cost: 0, portionEs: "Alitas ahumadas, bien especiadas, con un toque picante.", portionEn: "Smoked, well-spiced wings with a spicy kick.", img: null },
  { id: "coctel-camarones", es: "Cóctel de camarones", en: "Shrimp cocktail", section: "entradas", price: 8.5, cost: 0, portionEs: "Salsa de chili coreano y katsuobushi (bonito ahumado y curado).", portionEn: "Korean chili sauce and katsuobushi (smoked cured bonito).", img: null },
  { id: "ceviche", es: "Ceviche de langostino", en: "Prawn ceviche", section: "entradas", price: 10, cost: 0, portionEs: "Un clásico panameño, con chips de plátano.", portionEn: "A Panamanian classic, with plantain chips.", img: "/media/ceviche.webp" },
  { id: "boneless", es: "Boneless de pollo", en: "Chicken boneless", section: "entradas", price: 11, cost: 0, portionEs: "Apanados, con salsa BBQ.", portionEn: "Breaded, with BBQ sauce.", img: "/media/boneless.webp" },

  // ── Carnes / Aves / Pescados ────────────────────────────────
  { id: "pollo", es: "Pollo al carbón", en: "Charcoal chicken", section: "mains", price: 13, cost: 0, portionEs: "Media porción de pollo, más 1 acompañamiento.", portionEn: "Half chicken, plus 1 side.", img: "/media/pollo.webp" },
  { id: "burger", es: "Hamburguesa clásica steakhouse", en: "Classic steakhouse burger", section: "mains", price: 15, cost: 0, portionEs: "Carne Angus, cebolla caramelizada, bacon, lechuga, tomate, salsa steakhouse y pan brioche.", portionEn: "Angus beef, caramelized onion, bacon, lettuce, tomato, steakhouse sauce and brioche.", img: "/media/burger.webp" },
  { id: "picada", es: "Picada argentina", en: "Argentine grill platter", section: "mains", price: 35, cost: 0, portionEs: "N.Y., chorizo, pollo a la brasa y 1 acompañamiento (2 a 3 personas).", portionEn: "N.Y., chorizo, charcoal chicken and 1 side (serves 2–3).", img: "/media/parrillada.webp" },
  { id: "ribeye", es: "Rib-eye al carbón (nacional, libre de hormonas)", en: "Charcoal rib eye (hormone-free, national)", section: "mains", price: 25, cost: 0, portionEs: "Incluye 1 acompañamiento y chimichurri.", portionEn: "Includes 1 side and chimichurri.", img: "/media/ribeye.webp" },
  { id: "ribeye-angus", es: "Rib-eye al carbón (Angus importado)", en: "Charcoal rib eye (imported Angus)", section: "mains", price: 35, cost: 0, portionEs: "Incluye 1 acompañamiento y chimichurri.", portionEn: "Includes 1 side and chimichurri.", img: null },
  { id: "filete-albahaca", es: "Filete en salsa de albahaca y hongos (8 oz)", en: "Filet in herb mushroom sauce (8 oz)", section: "mains", price: 15, cost: 0, portionEs: "Cremosa salsa de hongos con albahaca y vino tinto. Incluye 1 acompañamiento.", portionEn: "Creamy mushroom sauce with basil and red wine. Includes 1 side.", img: null },
  { id: "ny-strip", es: "N.Y. strip al carbón (USDA Choice importado)", en: "Charcoal N.Y. strip (imported USDA Choice)", section: "mains", price: 28, cost: 0, portionEs: "Incluye 1 acompañamiento y chimichurri.", portionEn: "Includes 1 side and chimichurri.", img: null },
  { id: "pulpo-caribe", es: "Pulpo caribe", en: "Caribbean octopus", section: "mains", price: 18, cost: 0, portionEs: "En leche de coco y curry, con patacones.", portionEn: "In coconut milk and curry, with patacones.", img: null },
  { id: "salmon", es: "Salmón a la parrilla", en: "Grilled salmon", section: "mains", price: 17, cost: 0, portionEs: "Incluye 1 acompañamiento.", portionEn: "Includes 1 side.", img: "/media/salmon.webp" },

  // ── Menú kids ───────────────────────────────────────────────
  { id: "kids-burger", es: "Mini hamburguesa Quinta Pata", en: "Quinta Pata mini burger", section: "kids", price: 6, cost: 0, portionEs: "1 unid. Incluye 1 acompañamiento.", portionEn: "1 pc. Includes 1 side.", img: "/media/kids-burger.webp" },
  { id: "kids-boneless", es: "Boneless de pollo (kids)", en: "Kids boneless", section: "kids", price: 6, cost: 0, portionEs: "Incluye 1 acompañamiento.", portionEn: "Includes 1 side.", img: "/media/kids-boneless.webp" },

  // ── Acompañamientos ─────────────────────────────────────────
  { id: "papas", es: "Papitas fritas", en: "French fries", section: "sides", price: 3.5, cost: 0, portionEs: "6 oz.", portionEn: "6 oz.", img: "/media/papas.webp" },
  { id: "patacon", es: "Patacón pisao", en: "Patacones", section: "sides", price: 3.5, cost: 0, portionEs: "Plátano y medio, cerca de seis patacones.", portionEn: "One and a half plantains, about six pieces.", img: "/media/patacon.webp" },
  { id: "yuca", es: "Yuca frita", en: "Fried cassava", section: "sides", price: 3.5, cost: 0, portionEs: "6 oz servidos.", portionEn: "6 oz served.", img: "/media/yuca.webp" },
  { id: "guacamole", es: "Guacamole", en: "Guacamole", section: "sides", price: 3.5, cost: 0, portionEs: "6 oz.", portionEn: "6 oz.", img: null },
  { id: "vegetales", es: "Vegetales al grill en mantequilla negra", en: "Grilled vegetables in black butter", section: "sides", price: 4.5, cost: 0, portionEs: "6 oz.", portionEn: "6 oz.", img: "/media/vegetales.webp" },
  { id: "totopos", es: "Totopos", en: "Tortilla chips", section: "sides", price: 3.5, cost: 0, portionEs: "Cinco tortillas.", portionEn: "Five tortillas.", img: "/media/totopos.webp" },

  // ── Empacados al vacío (para llevar) ─────────────────────────
  { id: "costillas-bbq-kc", es: "Costillas BBQ estilo Kansas City", en: "Kansas City BBQ ribs", section: "empacados", price: 8, cost: 0, portionEs: "15 horas de cocción, ahumadas en nance.", portionEn: "15-hour cook, smoked over nance wood.", img: null },
  { id: "alitas-jerk-vacio", es: "Alitas estilo jerk jamaiquino", en: "Jamaican jerk wings", section: "empacados", price: 10.5, cost: 0, portionEs: "Alitas ahumadas, bien especiadas, con un toque picante.", portionEn: "Smoked, well-spiced wings with a spicy kick.", img: null },
  { id: "pulpo-caribe-vacio", es: "Pulpo caribe", en: "Caribbean octopus", section: "empacados", price: 17, cost: 0, portionEs: "En leche de coco y curry.", portionEn: "In coconut milk and curry.", img: null },
  { id: "filete-albahaca-vacio", es: "Filete en salsa de albahaca y hongos (8 oz)", en: "Filet in herb mushroom sauce (8 oz)", section: "empacados", price: 14, cost: 0, portionEs: "Cremosa salsa de hongos con albahaca y vino tinto.", portionEn: "Creamy mushroom sauce with basil and red wine.", img: null },
  { id: "vegetales-grill-vacio", es: "Vegetales al grill en mantequilla negra", en: "Grilled vegetables in black butter", section: "empacados", price: 4.5, cost: 0, portionEs: "6 oz.", portionEn: "6 oz.", img: "/media/vegetales.webp" },
    ],
  },
  booking: {
    slots: ["18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30"],
    closedWeekdays: [],
    coversPerSlot: 24,
    autoConfirmMaxParty: 8,
    maxParty: 20,
    bookAheadDays: 90,
    minLeadMinutes: 60,
  },
  agent: {
    kind: "Gastrobar de parrilla, picadas y barra",
    payments: "Visa, Mastercard, efectivo, Yappy",
    amenities: "Estacionamiento, Wi-Fi",
    facts: [
      "Parrilla, picadas y barra. Cócteles de la casa.",
      "Pantallas para fútbol en vivo.",
      "Música en vivo algunas noches; se anuncia en Instagram.",
      "Se puede llegar sin reserva; para grupos es mejor reservar.",
      "Precios en USD con ITBMS incluido.",
    ],
  },
  books: { cocina, barra },
};

export default venue;
