// Regenerate src/lib/casa-files.data.server.ts from private/casa/*.xlsx.
// Run after replacing a workbook:  node scripts/embed-casa.mjs
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
const dir = new URL("../private/casa/", import.meta.url);
const files = readdirSync(dir).filter((f) => f.endsWith(".xlsx")).sort();
const body = files
  .map((f) => `  ${JSON.stringify(f)}: ${JSON.stringify(readFileSync(new URL(f, dir)).toString("base64"))},`)
  .join("\n");
writeFileSync(
  new URL("../src/lib/casa-files.data.server.ts", import.meta.url),
  `// GENERATED by scripts/embed-casa.mjs — do not edit. Server-only.\nexport const CASA_FILES: Record<string, string> = {\n${body}\n};\n`,
);
console.log(`embedded ${files.length} workbook(s)`);
