/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CasaFileRouteImport } from './routes/casa/$file'
import { Route as OpinionTokenRouteImport } from './routes/opinion.$token'
import { Route as ApiAgentChatRouteImport } from './routes/api/agent/chat'
import { Route as ApiAgentTelegramRouteImport } from './routes/api/agent/telegram'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaFileRoute = CasaFileRouteImport.update({
  id: '/casa/$file',
  path: '/casa/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinionTokenRoute = OpinionTokenRouteImport.update({
  id: '/opinion/$token',
  path: '/opinion/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentChatRoute = ApiAgentChatRouteImport.update({
  id: '/api/agent/chat',
  path: '/api/agent/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentTelegramRoute = ApiAgentTelegramRouteImport.update({
  id: '/api/agent/telegram',
  path: '/api/agent/telegram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/casa/$file': typeof CasaFileRoute
  '/opinion/$token': typeof OpinionTokenRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/telegram': typeof ApiAgentTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/casa/$file': typeof CasaFileRoute
  '/opinion/$token': typeof OpinionTokenRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/telegram': typeof ApiAgentTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/casa/$file': typeof CasaFileRoute
  '/opinion/$token': typeof OpinionTokenRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/telegram': typeof ApiAgentTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/casa/$file'
    | '/opinion/$token'
    | '/api/agent/chat'
    | '/api/agent/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/casa/$file'
    | '/opinion/$token'
    | '/api/agent/chat'
    | '/api/agent/telegram'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/casa/$file'
    | '/opinion/$token'
    | '/api/agent/chat'
    | '/api/agent/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CasaFileRoute: typeof CasaFileRoute
  OpinionTokenRoute: typeof OpinionTokenRoute
  ApiAgentChatRoute: typeof ApiAgentChatRoute
  ApiAgentTelegramRoute: typeof ApiAgentTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa/$file': {
      id: '/casa/$file'
      path: '/casa/$file'
      fullPath: '/casa/$file'
      preLoaderRoute: typeof CasaFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinion/$token': {
      id: '/opinion/$token'
      path: '/opinion/$token'
      fullPath: '/opinion/$token'
      preLoaderRoute: typeof OpinionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/chat': {
      id: '/api/agent/chat'
      path: '/api/agent/chat'
      fullPath: '/api/agent/chat'
      preLoaderRoute: typeof ApiAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/telegram': {
      id: '/api/agent/telegram'
      path: '/api/agent/telegram'
      fullPath: '/api/agent/telegram'
      preLoaderRoute: typeof ApiAgentTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CasaFileRoute: CasaFileRoute,
  OpinionTokenRoute: OpinionTokenRoute,
  ApiAgentChatRoute: ApiAgentChatRoute,
  ApiAgentTelegramRoute: ApiAgentTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
